// Code generated by ent, DO NOT EDIT.

package interaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/predicate"
	"github.com/rs/xid"
)

// ID filters vertices based on their ID field.
func ID(id xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldLTE(FieldID, id))
}

// DeploymentID applies equality check predicate on the "deployment_id" field. It's identical to DeploymentIDEQ.
func DeploymentID(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldDeploymentID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldTenantID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldEventType, v))
}

// Query applies equality check predicate on the "query" field. It's identical to QueryEQ.
func Query(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldQuery, v))
}

// Answer applies equality check predicate on the "answer" field. It's identical to AnswerEQ.
func Answer(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldAnswer, v))
}

// Helpful applies equality check predicate on the "helpful" field. It's identical to HelpfulEQ.
func Helpful(v bool) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldHelpful, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldDurationMs, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldCreatedAt, v))
}

// DeploymentIDEQ applies the EQ predicate on the "deployment_id" field.
func DeploymentIDEQ(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldDeploymentID, v))
}

// DeploymentIDNEQ applies the NEQ predicate on the "deployment_id" field.
func DeploymentIDNEQ(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldNEQ(FieldDeploymentID, v))
}

// DeploymentIDIn applies the In predicate on the "deployment_id" field.
func DeploymentIDIn(vs ...xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldIn(FieldDeploymentID, vs...))
}

// DeploymentIDNotIn applies the NotIn predicate on the "deployment_id" field.
func DeploymentIDNotIn(vs ...xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldNotIn(FieldDeploymentID, vs...))
}

// DeploymentIDGT applies the GT predicate on the "deployment_id" field.
func DeploymentIDGT(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldGT(FieldDeploymentID, v))
}

// DeploymentIDGTE applies the GTE predicate on the "deployment_id" field.
func DeploymentIDGTE(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldGTE(FieldDeploymentID, v))
}

// DeploymentIDLT applies the LT predicate on the "deployment_id" field.
func DeploymentIDLT(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldLT(FieldDeploymentID, v))
}

// DeploymentIDLTE applies the LTE predicate on the "deployment_id" field.
func DeploymentIDLTE(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldLTE(FieldDeploymentID, v))
}

// DeploymentIDContains applies the Contains predicate on the "deployment_id" field.
func DeploymentIDContains(v xid.ID) predicate.Interaction {
	vc := v.String()
	return predicate.Interaction(sql.FieldContains(FieldDeploymentID, vc))
}

// DeploymentIDHasPrefix applies the HasPrefix predicate on the "deployment_id" field.
func DeploymentIDHasPrefix(v xid.ID) predicate.Interaction {
	vc := v.String()
	return predicate.Interaction(sql.FieldHasPrefix(FieldDeploymentID, vc))
}

// DeploymentIDHasSuffix applies the HasSuffix predicate on the "deployment_id" field.
func DeploymentIDHasSuffix(v xid.ID) predicate.Interaction {
	vc := v.String()
	return predicate.Interaction(sql.FieldHasSuffix(FieldDeploymentID, vc))
}

// DeploymentIDIsNil applies the IsNil predicate on the "deployment_id" field.
func DeploymentIDIsNil() predicate.Interaction {
	return predicate.Interaction(sql.FieldIsNull(FieldDeploymentID))
}

// DeploymentIDNotNil applies the NotNil predicate on the "deployment_id" field.
func DeploymentIDNotNil() predicate.Interaction {
	return predicate.Interaction(sql.FieldNotNull(FieldDeploymentID))
}

// DeploymentIDEqualFold applies the EqualFold predicate on the "deployment_id" field.
func DeploymentIDEqualFold(v xid.ID) predicate.Interaction {
	vc := v.String()
	return predicate.Interaction(sql.FieldEqualFold(FieldDeploymentID, vc))
}

// DeploymentIDContainsFold applies the ContainsFold predicate on the "deployment_id" field.
func DeploymentIDContainsFold(v xid.ID) predicate.Interaction {
	vc := v.String()
	return predicate.Interaction(sql.FieldContainsFold(FieldDeploymentID, vc))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v xid.ID) predicate.Interaction {
	return predicate.Interaction(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v xid.ID) predicate.Interaction {
	vc := v.String()
	return predicate.Interaction(sql.FieldContains(FieldTenantID, vc))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v xid.ID) predicate.Interaction {
	vc := v.String()
	return predicate.Interaction(sql.FieldHasPrefix(FieldTenantID, vc))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v xid.ID) predicate.Interaction {
	vc := v.String()
	return predicate.Interaction(sql.FieldHasSuffix(FieldTenantID, vc))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v xid.ID) predicate.Interaction {
	vc := v.String()
	return predicate.Interaction(sql.FieldEqualFold(FieldTenantID, vc))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v xid.ID) predicate.Interaction {
	vc := v.String()
	return predicate.Interaction(sql.FieldContainsFold(FieldTenantID, vc))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.Interaction {
	return predicate.Interaction(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.Interaction {
	return predicate.Interaction(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldContainsFold(FieldEventType, v))
}

// QueryEQ applies the EQ predicate on the "query" field.
func QueryEQ(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldQuery, v))
}

// QueryNEQ applies the NEQ predicate on the "query" field.
func QueryNEQ(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldNEQ(FieldQuery, v))
}

// QueryIn applies the In predicate on the "query" field.
func QueryIn(vs ...string) predicate.Interaction {
	return predicate.Interaction(sql.FieldIn(FieldQuery, vs...))
}

// QueryNotIn applies the NotIn predicate on the "query" field.
func QueryNotIn(vs ...string) predicate.Interaction {
	return predicate.Interaction(sql.FieldNotIn(FieldQuery, vs...))
}

// QueryGT applies the GT predicate on the "query" field.
func QueryGT(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldGT(FieldQuery, v))
}

// QueryGTE applies the GTE predicate on the "query" field.
func QueryGTE(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldGTE(FieldQuery, v))
}

// QueryLT applies the LT predicate on the "query" field.
func QueryLT(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldLT(FieldQuery, v))
}

// QueryLTE applies the LTE predicate on the "query" field.
func QueryLTE(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldLTE(FieldQuery, v))
}

// QueryContains applies the Contains predicate on the "query" field.
func QueryContains(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldContains(FieldQuery, v))
}

// QueryHasPrefix applies the HasPrefix predicate on the "query" field.
func QueryHasPrefix(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldHasPrefix(FieldQuery, v))
}

// QueryHasSuffix applies the HasSuffix predicate on the "query" field.
func QueryHasSuffix(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldHasSuffix(FieldQuery, v))
}

// QueryEqualFold applies the EqualFold predicate on the "query" field.
func QueryEqualFold(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldEqualFold(FieldQuery, v))
}

// QueryContainsFold applies the ContainsFold predicate on the "query" field.
func QueryContainsFold(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldContainsFold(FieldQuery, v))
}

// AnswerEQ applies the EQ predicate on the "answer" field.
func AnswerEQ(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldAnswer, v))
}

// AnswerNEQ applies the NEQ predicate on the "answer" field.
func AnswerNEQ(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldNEQ(FieldAnswer, v))
}

// AnswerIn applies the In predicate on the "answer" field.
func AnswerIn(vs ...string) predicate.Interaction {
	return predicate.Interaction(sql.FieldIn(FieldAnswer, vs...))
}

// AnswerNotIn applies the NotIn predicate on the "answer" field.
func AnswerNotIn(vs ...string) predicate.Interaction {
	return predicate.Interaction(sql.FieldNotIn(FieldAnswer, vs...))
}

// AnswerGT applies the GT predicate on the "answer" field.
func AnswerGT(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldGT(FieldAnswer, v))
}

// AnswerGTE applies the GTE predicate on the "answer" field.
func AnswerGTE(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldGTE(FieldAnswer, v))
}

// AnswerLT applies the LT predicate on the "answer" field.
func AnswerLT(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldLT(FieldAnswer, v))
}

// AnswerLTE applies the LTE predicate on the "answer" field.
func AnswerLTE(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldLTE(FieldAnswer, v))
}

// AnswerContains applies the Contains predicate on the "answer" field.
func AnswerContains(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldContains(FieldAnswer, v))
}

// AnswerHasPrefix applies the HasPrefix predicate on the "answer" field.
func AnswerHasPrefix(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldHasPrefix(FieldAnswer, v))
}

// AnswerHasSuffix applies the HasSuffix predicate on the "answer" field.
func AnswerHasSuffix(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldHasSuffix(FieldAnswer, v))
}

// AnswerIsNil applies the IsNil predicate on the "answer" field.
func AnswerIsNil() predicate.Interaction {
	return predicate.Interaction(sql.FieldIsNull(FieldAnswer))
}

// AnswerNotNil applies the NotNil predicate on the "answer" field.
func AnswerNotNil() predicate.Interaction {
	return predicate.Interaction(sql.FieldNotNull(FieldAnswer))
}

// AnswerEqualFold applies the EqualFold predicate on the "answer" field.
func AnswerEqualFold(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldEqualFold(FieldAnswer, v))
}

// AnswerContainsFold applies the ContainsFold predicate on the "answer" field.
func AnswerContainsFold(v string) predicate.Interaction {
	return predicate.Interaction(sql.FieldContainsFold(FieldAnswer, v))
}

// HelpfulEQ applies the EQ predicate on the "helpful" field.
func HelpfulEQ(v bool) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldHelpful, v))
}

// HelpfulNEQ applies the NEQ predicate on the "helpful" field.
func HelpfulNEQ(v bool) predicate.Interaction {
	return predicate.Interaction(sql.FieldNEQ(FieldHelpful, v))
}

// HelpfulIsNil applies the IsNil predicate on the "helpful" field.
func HelpfulIsNil() predicate.Interaction {
	return predicate.Interaction(sql.FieldIsNull(FieldHelpful))
}

// HelpfulNotNil applies the NotNil predicate on the "helpful" field.
func HelpfulNotNil() predicate.Interaction {
	return predicate.Interaction(sql.FieldNotNull(FieldHelpful))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.Interaction {
	return predicate.Interaction(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.Interaction {
	return predicate.Interaction(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.Interaction {
	return predicate.Interaction(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.Interaction {
	return predicate.Interaction(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.Interaction {
	return predicate.Interaction(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.Interaction {
	return predicate.Interaction(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.Interaction {
	return predicate.Interaction(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.Interaction {
	return predicate.Interaction(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.Interaction {
	return predicate.Interaction(sql.FieldNotNull(FieldDurationMs))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Interaction {
	return predicate.Interaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Interaction {
	return predicate.Interaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Interaction {
	return predicate.Interaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Interaction {
	return predicate.Interaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Interaction {
	return predicate.Interaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Interaction {
	return predicate.Interaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Interaction {
	return predicate.Interaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Interaction {
	return predicate.Interaction(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Interaction) predicate.Interaction {
	return predicate.Interaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Interaction) predicate.Interaction {
	return predicate.Interaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Interaction) predicate.Interaction {
	return predicate.Interaction(sql.NotPredicates(p))
}
