// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chunk is the predicate function for chunk builders.
type Chunk func(*sql.Selector)

// Deployment is the predicate function for deployment builders.
type Deployment func(*sql.Selector)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// IngestJob is the predicate function for ingestjob builders.
type IngestJob func(*sql.Selector)

// Interaction is the predicate function for interaction builders.
type Interaction func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)
