// Code generated by ent, DO NOT EDIT.

package document

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rs/xid"
)

const (
	// Label holds the string label denoting the document type in the database.
	Label = "document"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSourceURL holds the string denoting the source_url field in the database.
	FieldSourceURL = "source_url"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldNormalizedHash holds the string denoting the normalized_hash field in the database.
	FieldNormalizedHash = "normalized_hash"
	// FieldDocType holds the string denoting the doc_type field in the database.
	FieldDocType = "doc_type"
	// FieldContentType holds the string denoting the content_type field in the database.
	FieldContentType = "content_type"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldDuplicateOf holds the string denoting the duplicate_of field in the database.
	FieldDuplicateOf = "duplicate_of"
	// FieldHasPii holds the string denoting the has_pii field in the database.
	FieldHasPii = "has_pii"
	// FieldPiiSummary holds the string denoting the pii_summary field in the database.
	FieldPiiSummary = "pii_summary"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeChunks holds the string denoting the chunks edge name in mutations.
	EdgeChunks = "chunks"
	// Table holds the table name of the document in the database.
	Table = "documents"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "documents"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// ChunksTable is the table that holds the chunks relation/edge.
	ChunksTable = "chunks"
	// ChunksInverseTable is the table name for the Chunk entity.
	// It exists in this package in order to avoid circular dependency with the "chunk" package.
	ChunksInverseTable = "chunks"
	// ChunksColumn is the table column denoting the chunks relation/edge.
	ChunksColumn = "document_id"
)

// Columns holds all SQL columns for document fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldTitle,
	FieldSourceURL,
	FieldMetadata,
	FieldNormalizedHash,
	FieldDocType,
	FieldContentType,
	FieldSize,
	FieldDuplicateOf,
	FieldHasPii,
	FieldPiiSummary,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDocType holds the default value on creation for the "doc_type" field.
	DefaultDocType string
	// DefaultHasPii holds the default value on creation for the "has_pii" field.
	DefaultHasPii bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() xid.ID
)

// OrderOption defines the ordering options for the Document queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySourceURL orders the results by the source_url field.
func BySourceURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceURL, opts...).ToFunc()
}

// ByNormalizedHash orders the results by the normalized_hash field.
func ByNormalizedHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNormalizedHash, opts...).ToFunc()
}

// ByDocType orders the results by the doc_type field.
func ByDocType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocType, opts...).ToFunc()
}

// ByContentType orders the results by the content_type field.
func ByContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentType, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByDuplicateOf orders the results by the duplicate_of field.
func ByDuplicateOf(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuplicateOf, opts...).ToFunc()
}

// ByHasPii orders the results by the has_pii field.
func ByHasPii(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasPii, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByChunksCount orders the results by chunks count.
func ByChunksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChunksStep(), opts...)
	}
}

// ByChunks orders the results by chunks terms.
func ByChunks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChunksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newChunksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChunksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChunksTable, ChunksColumn),
	)
}
