// Code generated by ent, DO NOT EDIT.

package document

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/predicate"
	"github.com/rs/xid"
)

// ID filters vertices based on their ID field.
func ID(id xid.ID) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id xid.ID) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id xid.ID) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...xid.ID) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...xid.ID) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id xid.ID) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id xid.ID) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id xid.ID) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id xid.ID) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldTenantID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldTitle, v))
}

// SourceURL applies equality check predicate on the "source_url" field. It's identical to SourceURLEQ.
func SourceURL(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldSourceURL, v))
}

// NormalizedHash applies equality check predicate on the "normalized_hash" field. It's identical to NormalizedHashEQ.
func NormalizedHash(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldNormalizedHash, v))
}

// DocType applies equality check predicate on the "doc_type" field. It's identical to DocTypeEQ.
func DocType(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDocType, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldContentType, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldSize, v))
}

// DuplicateOf applies equality check predicate on the "duplicate_of" field. It's identical to DuplicateOfEQ.
func DuplicateOf(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDuplicateOf, v))
}

// HasPii applies equality check predicate on the "has_pii" field. It's identical to HasPiiEQ.
func HasPii(v bool) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldHasPii, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...xid.ID) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...xid.ID) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v xid.ID) predicate.Document {
	vc := v.String()
	return predicate.Document(sql.FieldContains(FieldTenantID, vc))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v xid.ID) predicate.Document {
	vc := v.String()
	return predicate.Document(sql.FieldHasPrefix(FieldTenantID, vc))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v xid.ID) predicate.Document {
	vc := v.String()
	return predicate.Document(sql.FieldHasSuffix(FieldTenantID, vc))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v xid.ID) predicate.Document {
	vc := v.String()
	return predicate.Document(sql.FieldEqualFold(FieldTenantID, vc))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v xid.ID) predicate.Document {
	vc := v.String()
	return predicate.Document(sql.FieldContainsFold(FieldTenantID, vc))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldTitle, v))
}

// SourceURLEQ applies the EQ predicate on the "source_url" field.
func SourceURLEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldSourceURL, v))
}

// SourceURLNEQ applies the NEQ predicate on the "source_url" field.
func SourceURLNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldSourceURL, v))
}

// SourceURLIn applies the In predicate on the "source_url" field.
func SourceURLIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldSourceURL, vs...))
}

// SourceURLNotIn applies the NotIn predicate on the "source_url" field.
func SourceURLNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldSourceURL, vs...))
}

// SourceURLGT applies the GT predicate on the "source_url" field.
func SourceURLGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldSourceURL, v))
}

// SourceURLGTE applies the GTE predicate on the "source_url" field.
func SourceURLGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldSourceURL, v))
}

// SourceURLLT applies the LT predicate on the "source_url" field.
func SourceURLLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldSourceURL, v))
}

// SourceURLLTE applies the LTE predicate on the "source_url" field.
func SourceURLLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldSourceURL, v))
}

// SourceURLContains applies the Contains predicate on the "source_url" field.
func SourceURLContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldSourceURL, v))
}

// SourceURLHasPrefix applies the HasPrefix predicate on the "source_url" field.
func SourceURLHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldSourceURL, v))
}

// SourceURLHasSuffix applies the HasSuffix predicate on the "source_url" field.
func SourceURLHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldSourceURL, v))
}

// SourceURLIsNil applies the IsNil predicate on the "source_url" field.
func SourceURLIsNil() predicate.Document {
	return predicate.Document(sql.FieldIsNull(FieldSourceURL))
}

// SourceURLNotNil applies the NotNil predicate on the "source_url" field.
func SourceURLNotNil() predicate.Document {
	return predicate.Document(sql.FieldNotNull(FieldSourceURL))
}

// SourceURLEqualFold applies the EqualFold predicate on the "source_url" field.
func SourceURLEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldSourceURL, v))
}

// SourceURLContainsFold applies the ContainsFold predicate on the "source_url" field.
func SourceURLContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldSourceURL, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Document {
	return predicate.Document(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Document {
	return predicate.Document(sql.FieldNotNull(FieldMetadata))
}

// NormalizedHashEQ applies the EQ predicate on the "normalized_hash" field.
func NormalizedHashEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldNormalizedHash, v))
}

// NormalizedHashNEQ applies the NEQ predicate on the "normalized_hash" field.
func NormalizedHashNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldNormalizedHash, v))
}

// NormalizedHashIn applies the In predicate on the "normalized_hash" field.
func NormalizedHashIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldNormalizedHash, vs...))
}

// NormalizedHashNotIn applies the NotIn predicate on the "normalized_hash" field.
func NormalizedHashNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldNormalizedHash, vs...))
}

// NormalizedHashGT applies the GT predicate on the "normalized_hash" field.
func NormalizedHashGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldNormalizedHash, v))
}

// NormalizedHashGTE applies the GTE predicate on the "normalized_hash" field.
func NormalizedHashGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldNormalizedHash, v))
}

// NormalizedHashLT applies the LT predicate on the "normalized_hash" field.
func NormalizedHashLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldNormalizedHash, v))
}

// NormalizedHashLTE applies the LTE predicate on the "normalized_hash" field.
func NormalizedHashLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldNormalizedHash, v))
}

// NormalizedHashContains applies the Contains predicate on the "normalized_hash" field.
func NormalizedHashContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldNormalizedHash, v))
}

// NormalizedHashHasPrefix applies the HasPrefix predicate on the "normalized_hash" field.
func NormalizedHashHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldNormalizedHash, v))
}

// NormalizedHashHasSuffix applies the HasSuffix predicate on the "normalized_hash" field.
func NormalizedHashHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldNormalizedHash, v))
}

// NormalizedHashIsNil applies the IsNil predicate on the "normalized_hash" field.
func NormalizedHashIsNil() predicate.Document {
	return predicate.Document(sql.FieldIsNull(FieldNormalizedHash))
}

// NormalizedHashNotNil applies the NotNil predicate on the "normalized_hash" field.
func NormalizedHashNotNil() predicate.Document {
	return predicate.Document(sql.FieldNotNull(FieldNormalizedHash))
}

// NormalizedHashEqualFold applies the EqualFold predicate on the "normalized_hash" field.
func NormalizedHashEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldNormalizedHash, v))
}

// NormalizedHashContainsFold applies the ContainsFold predicate on the "normalized_hash" field.
func NormalizedHashContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldNormalizedHash, v))
}

// DocTypeEQ applies the EQ predicate on the "doc_type" field.
func DocTypeEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDocType, v))
}

// DocTypeNEQ applies the NEQ predicate on the "doc_type" field.
func DocTypeNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldDocType, v))
}

// DocTypeIn applies the In predicate on the "doc_type" field.
func DocTypeIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldDocType, vs...))
}

// DocTypeNotIn applies the NotIn predicate on the "doc_type" field.
func DocTypeNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldDocType, vs...))
}

// DocTypeGT applies the GT predicate on the "doc_type" field.
func DocTypeGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldDocType, v))
}

// DocTypeGTE applies the GTE predicate on the "doc_type" field.
func DocTypeGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldDocType, v))
}

// DocTypeLT applies the LT predicate on the "doc_type" field.
func DocTypeLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldDocType, v))
}

// DocTypeLTE applies the LTE predicate on the "doc_type" field.
func DocTypeLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldDocType, v))
}

// DocTypeContains applies the Contains predicate on the "doc_type" field.
func DocTypeContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldDocType, v))
}

// DocTypeHasPrefix applies the HasPrefix predicate on the "doc_type" field.
func DocTypeHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldDocType, v))
}

// DocTypeHasSuffix applies the HasSuffix predicate on the "doc_type" field.
func DocTypeHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldDocType, v))
}

// DocTypeEqualFold applies the EqualFold predicate on the "doc_type" field.
func DocTypeEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldDocType, v))
}

// DocTypeContainsFold applies the ContainsFold predicate on the "doc_type" field.
func DocTypeContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldDocType, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.Document {
	return predicate.Document(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.Document {
	return predicate.Document(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeIsNil applies the IsNil predicate on the "content_type" field.
func ContentTypeIsNil() predicate.Document {
	return predicate.Document(sql.FieldIsNull(FieldContentType))
}

// ContentTypeNotNil applies the NotNil predicate on the "content_type" field.
func ContentTypeNotNil() predicate.Document {
	return predicate.Document(sql.FieldNotNull(FieldContentType))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.Document {
	return predicate.Document(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.Document {
	return predicate.Document(sql.FieldContainsFold(FieldContentType, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.Document {
	return predicate.Document(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.Document {
	return predicate.Document(sql.FieldNotNull(FieldSize))
}

// DuplicateOfEQ applies the EQ predicate on the "duplicate_of" field.
func DuplicateOfEQ(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldDuplicateOf, v))
}

// DuplicateOfNEQ applies the NEQ predicate on the "duplicate_of" field.
func DuplicateOfNEQ(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldDuplicateOf, v))
}

// DuplicateOfIn applies the In predicate on the "duplicate_of" field.
func DuplicateOfIn(vs ...xid.ID) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldDuplicateOf, vs...))
}

// DuplicateOfNotIn applies the NotIn predicate on the "duplicate_of" field.
func DuplicateOfNotIn(vs ...xid.ID) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldDuplicateOf, vs...))
}

// DuplicateOfGT applies the GT predicate on the "duplicate_of" field.
func DuplicateOfGT(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldDuplicateOf, v))
}

// DuplicateOfGTE applies the GTE predicate on the "duplicate_of" field.
func DuplicateOfGTE(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldDuplicateOf, v))
}

// DuplicateOfLT applies the LT predicate on the "duplicate_of" field.
func DuplicateOfLT(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldDuplicateOf, v))
}

// DuplicateOfLTE applies the LTE predicate on the "duplicate_of" field.
func DuplicateOfLTE(v xid.ID) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldDuplicateOf, v))
}

// DuplicateOfContains applies the Contains predicate on the "duplicate_of" field.
func DuplicateOfContains(v xid.ID) predicate.Document {
	vc := v.String()
	return predicate.Document(sql.FieldContains(FieldDuplicateOf, vc))
}

// DuplicateOfHasPrefix applies the HasPrefix predicate on the "duplicate_of" field.
func DuplicateOfHasPrefix(v xid.ID) predicate.Document {
	vc := v.String()
	return predicate.Document(sql.FieldHasPrefix(FieldDuplicateOf, vc))
}

// DuplicateOfHasSuffix applies the HasSuffix predicate on the "duplicate_of" field.
func DuplicateOfHasSuffix(v xid.ID) predicate.Document {
	vc := v.String()
	return predicate.Document(sql.FieldHasSuffix(FieldDuplicateOf, vc))
}

// DuplicateOfIsNil applies the IsNil predicate on the "duplicate_of" field.
func DuplicateOfIsNil() predicate.Document {
	return predicate.Document(sql.FieldIsNull(FieldDuplicateOf))
}

// DuplicateOfNotNil applies the NotNil predicate on the "duplicate_of" field.
func DuplicateOfNotNil() predicate.Document {
	return predicate.Document(sql.FieldNotNull(FieldDuplicateOf))
}

// DuplicateOfEqualFold applies the EqualFold predicate on the "duplicate_of" field.
func DuplicateOfEqualFold(v xid.ID) predicate.Document {
	vc := v.String()
	return predicate.Document(sql.FieldEqualFold(FieldDuplicateOf, vc))
}

// DuplicateOfContainsFold applies the ContainsFold predicate on the "duplicate_of" field.
func DuplicateOfContainsFold(v xid.ID) predicate.Document {
	vc := v.String()
	return predicate.Document(sql.FieldContainsFold(FieldDuplicateOf, vc))
}

// HasPiiEQ applies the EQ predicate on the "has_pii" field.
func HasPiiEQ(v bool) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldHasPii, v))
}

// HasPiiNEQ applies the NEQ predicate on the "has_pii" field.
func HasPiiNEQ(v bool) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldHasPii, v))
}

// PiiSummaryIsNil applies the IsNil predicate on the "pii_summary" field.
func PiiSummaryIsNil() predicate.Document {
	return predicate.Document(sql.FieldIsNull(FieldPiiSummary))
}

// PiiSummaryNotNil applies the NotNil predicate on the "pii_summary" field.
func PiiSummaryNotNil() predicate.Document {
	return predicate.Document(sql.FieldNotNull(FieldPiiSummary))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Document {
	return predicate.Document(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Document {
	return predicate.Document(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Document {
	return predicate.Document(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChunks applies the HasEdge predicate on the "chunks" edge.
func HasChunks() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChunksTable, ChunksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChunksWith applies the HasEdge predicate on the "chunks" edge with a given conditions (other predicates).
func HasChunksWith(preds ...predicate.Chunk) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		step := newChunksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Document) predicate.Document {
	return predicate.Document(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Document) predicate.Document {
	return predicate.Document(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Document) predicate.Document {
	return predicate.Document(sql.NotPredicates(p))
}
