// Code generated by ent, DO NOT EDIT.

package chunk

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rs/xid"
)

const (
	// Label holds the string label denoting the chunk type in the database.
	Label = "chunk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDocumentID holds the string denoting the document_id field in the database.
	FieldDocumentID = "document_id"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldEmbeddingModel holds the string denoting the embedding_model field in the database.
	FieldEmbeddingModel = "embedding_model"
	// FieldVectorID holds the string denoting the vector_id field in the database.
	FieldVectorID = "vector_id"
	// FieldEmbeddingInt8 holds the string denoting the embedding_int8 field in the database.
	FieldEmbeddingInt8 = "embedding_int8"
	// FieldEmbeddingBinary holds the string denoting the embedding_binary field in the database.
	FieldEmbeddingBinary = "embedding_binary"
	// EdgeDocument holds the string denoting the document edge name in mutations.
	EdgeDocument = "document"
	// Table holds the table name of the chunk in the database.
	Table = "chunks"
	// DocumentTable is the table that holds the document relation/edge.
	DocumentTable = "chunks"
	// DocumentInverseTable is the table name for the Document entity.
	// It exists in this package in order to avoid circular dependency with the "document" package.
	DocumentInverseTable = "documents"
	// DocumentColumn is the table column denoting the document relation/edge.
	DocumentColumn = "document_id"
)

// Columns holds all SQL columns for chunk fields.
var Columns = []string{
	FieldID,
	FieldDocumentID,
	FieldText,
	FieldMetadata,
	FieldEmbeddingModel,
	FieldVectorID,
	FieldEmbeddingInt8,
	FieldEmbeddingBinary,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TextValidator is a validator for the "text" field. It is called by the builders before save.
	TextValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() xid.ID
)

// OrderOption defines the ordering options for the Chunk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDocumentID orders the results by the document_id field.
func ByDocumentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentID, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// ByEmbeddingModel orders the results by the embedding_model field.
func ByEmbeddingModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmbeddingModel, opts...).ToFunc()
}

// ByVectorID orders the results by the vector_id field.
func ByVectorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVectorID, opts...).ToFunc()
}

// ByDocumentField orders the results by document field.
func ByDocumentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDocumentStep(), sql.OrderByField(field, opts...))
	}
}
func newDocumentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DocumentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DocumentTable, DocumentColumn),
	)
}
