// Code generated by ent, DO NOT EDIT.

package chunk

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/predicate"
	"github.com/rs/xid"
)

// ID filters vertices based on their ID field.
func ID(id xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldID, id))
}

// DocumentID applies equality check predicate on the "document_id" field. It's identical to DocumentIDEQ.
func DocumentID(v xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldDocumentID, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldText, v))
}

// EmbeddingModel applies equality check predicate on the "embedding_model" field. It's identical to EmbeddingModelEQ.
func EmbeddingModel(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldEmbeddingModel, v))
}

// VectorID applies equality check predicate on the "vector_id" field. It's identical to VectorIDEQ.
func VectorID(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldVectorID, v))
}

// EmbeddingInt8 applies equality check predicate on the "embedding_int8" field. It's identical to EmbeddingInt8EQ.
func EmbeddingInt8(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldEmbeddingInt8, v))
}

// EmbeddingBinary applies equality check predicate on the "embedding_binary" field. It's identical to EmbeddingBinaryEQ.
func EmbeddingBinary(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldEmbeddingBinary, v))
}

// DocumentIDEQ applies the EQ predicate on the "document_id" field.
func DocumentIDEQ(v xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldDocumentID, v))
}

// DocumentIDNEQ applies the NEQ predicate on the "document_id" field.
func DocumentIDNEQ(v xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldDocumentID, v))
}

// DocumentIDIn applies the In predicate on the "document_id" field.
func DocumentIDIn(vs ...xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldDocumentID, vs...))
}

// DocumentIDNotIn applies the NotIn predicate on the "document_id" field.
func DocumentIDNotIn(vs ...xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldDocumentID, vs...))
}

// DocumentIDGT applies the GT predicate on the "document_id" field.
func DocumentIDGT(v xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldDocumentID, v))
}

// DocumentIDGTE applies the GTE predicate on the "document_id" field.
func DocumentIDGTE(v xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldDocumentID, v))
}

// DocumentIDLT applies the LT predicate on the "document_id" field.
func DocumentIDLT(v xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldDocumentID, v))
}

// DocumentIDLTE applies the LTE predicate on the "document_id" field.
func DocumentIDLTE(v xid.ID) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldDocumentID, v))
}

// DocumentIDContains applies the Contains predicate on the "document_id" field.
func DocumentIDContains(v xid.ID) predicate.Chunk {
	vc := v.String()
	return predicate.Chunk(sql.FieldContains(FieldDocumentID, vc))
}

// DocumentIDHasPrefix applies the HasPrefix predicate on the "document_id" field.
func DocumentIDHasPrefix(v xid.ID) predicate.Chunk {
	vc := v.String()
	return predicate.Chunk(sql.FieldHasPrefix(FieldDocumentID, vc))
}

// DocumentIDHasSuffix applies the HasSuffix predicate on the "document_id" field.
func DocumentIDHasSuffix(v xid.ID) predicate.Chunk {
	vc := v.String()
	return predicate.Chunk(sql.FieldHasSuffix(FieldDocumentID, vc))
}

// DocumentIDEqualFold applies the EqualFold predicate on the "document_id" field.
func DocumentIDEqualFold(v xid.ID) predicate.Chunk {
	vc := v.String()
	return predicate.Chunk(sql.FieldEqualFold(FieldDocumentID, vc))
}

// DocumentIDContainsFold applies the ContainsFold predicate on the "document_id" field.
func DocumentIDContainsFold(v xid.ID) predicate.Chunk {
	vc := v.String()
	return predicate.Chunk(sql.FieldContainsFold(FieldDocumentID, vc))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldText, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldMetadata))
}

// EmbeddingModelEQ applies the EQ predicate on the "embedding_model" field.
func EmbeddingModelEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldEmbeddingModel, v))
}

// EmbeddingModelNEQ applies the NEQ predicate on the "embedding_model" field.
func EmbeddingModelNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldEmbeddingModel, v))
}

// EmbeddingModelIn applies the In predicate on the "embedding_model" field.
func EmbeddingModelIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldEmbeddingModel, vs...))
}

// EmbeddingModelNotIn applies the NotIn predicate on the "embedding_model" field.
func EmbeddingModelNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldEmbeddingModel, vs...))
}

// EmbeddingModelGT applies the GT predicate on the "embedding_model" field.
func EmbeddingModelGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldEmbeddingModel, v))
}

// EmbeddingModelGTE applies the GTE predicate on the "embedding_model" field.
func EmbeddingModelGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldEmbeddingModel, v))
}

// EmbeddingModelLT applies the LT predicate on the "embedding_model" field.
func EmbeddingModelLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldEmbeddingModel, v))
}

// EmbeddingModelLTE applies the LTE predicate on the "embedding_model" field.
func EmbeddingModelLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldEmbeddingModel, v))
}

// EmbeddingModelContains applies the Contains predicate on the "embedding_model" field.
func EmbeddingModelContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldEmbeddingModel, v))
}

// EmbeddingModelHasPrefix applies the HasPrefix predicate on the "embedding_model" field.
func EmbeddingModelHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldEmbeddingModel, v))
}

// EmbeddingModelHasSuffix applies the HasSuffix predicate on the "embedding_model" field.
func EmbeddingModelHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldEmbeddingModel, v))
}

// EmbeddingModelIsNil applies the IsNil predicate on the "embedding_model" field.
func EmbeddingModelIsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldEmbeddingModel))
}

// EmbeddingModelNotNil applies the NotNil predicate on the "embedding_model" field.
func EmbeddingModelNotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldEmbeddingModel))
}

// EmbeddingModelEqualFold applies the EqualFold predicate on the "embedding_model" field.
func EmbeddingModelEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldEmbeddingModel, v))
}

// EmbeddingModelContainsFold applies the ContainsFold predicate on the "embedding_model" field.
func EmbeddingModelContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldEmbeddingModel, v))
}

// VectorIDEQ applies the EQ predicate on the "vector_id" field.
func VectorIDEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldVectorID, v))
}

// VectorIDNEQ applies the NEQ predicate on the "vector_id" field.
func VectorIDNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldVectorID, v))
}

// VectorIDIn applies the In predicate on the "vector_id" field.
func VectorIDIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldVectorID, vs...))
}

// VectorIDNotIn applies the NotIn predicate on the "vector_id" field.
func VectorIDNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldVectorID, vs...))
}

// VectorIDGT applies the GT predicate on the "vector_id" field.
func VectorIDGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldVectorID, v))
}

// VectorIDGTE applies the GTE predicate on the "vector_id" field.
func VectorIDGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldVectorID, v))
}

// VectorIDLT applies the LT predicate on the "vector_id" field.
func VectorIDLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldVectorID, v))
}

// VectorIDLTE applies the LTE predicate on the "vector_id" field.
func VectorIDLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldVectorID, v))
}

// VectorIDContains applies the Contains predicate on the "vector_id" field.
func VectorIDContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldVectorID, v))
}

// VectorIDHasPrefix applies the HasPrefix predicate on the "vector_id" field.
func VectorIDHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldVectorID, v))
}

// VectorIDHasSuffix applies the HasSuffix predicate on the "vector_id" field.
func VectorIDHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldVectorID, v))
}

// VectorIDIsNil applies the IsNil predicate on the "vector_id" field.
func VectorIDIsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldVectorID))
}

// VectorIDNotNil applies the NotNil predicate on the "vector_id" field.
func VectorIDNotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldVectorID))
}

// VectorIDEqualFold applies the EqualFold predicate on the "vector_id" field.
func VectorIDEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldVectorID, v))
}

// VectorIDContainsFold applies the ContainsFold predicate on the "vector_id" field.
func VectorIDContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldVectorID, v))
}

// EmbeddingInt8EQ applies the EQ predicate on the "embedding_int8" field.
func EmbeddingInt8EQ(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldEmbeddingInt8, v))
}

// EmbeddingInt8NEQ applies the NEQ predicate on the "embedding_int8" field.
func EmbeddingInt8NEQ(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldEmbeddingInt8, v))
}

// EmbeddingInt8In applies the In predicate on the "embedding_int8" field.
func EmbeddingInt8In(vs ...[]byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldEmbeddingInt8, vs...))
}

// EmbeddingInt8NotIn applies the NotIn predicate on the "embedding_int8" field.
func EmbeddingInt8NotIn(vs ...[]byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldEmbeddingInt8, vs...))
}

// EmbeddingInt8GT applies the GT predicate on the "embedding_int8" field.
func EmbeddingInt8GT(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldEmbeddingInt8, v))
}

// EmbeddingInt8GTE applies the GTE predicate on the "embedding_int8" field.
func EmbeddingInt8GTE(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldEmbeddingInt8, v))
}

// EmbeddingInt8LT applies the LT predicate on the "embedding_int8" field.
func EmbeddingInt8LT(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldEmbeddingInt8, v))
}

// EmbeddingInt8LTE applies the LTE predicate on the "embedding_int8" field.
func EmbeddingInt8LTE(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldEmbeddingInt8, v))
}

// EmbeddingInt8IsNil applies the IsNil predicate on the "embedding_int8" field.
func EmbeddingInt8IsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldEmbeddingInt8))
}

// EmbeddingInt8NotNil applies the NotNil predicate on the "embedding_int8" field.
func EmbeddingInt8NotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldEmbeddingInt8))
}

// EmbeddingBinaryEQ applies the EQ predicate on the "embedding_binary" field.
func EmbeddingBinaryEQ(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldEmbeddingBinary, v))
}

// EmbeddingBinaryNEQ applies the NEQ predicate on the "embedding_binary" field.
func EmbeddingBinaryNEQ(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldEmbeddingBinary, v))
}

// EmbeddingBinaryIn applies the In predicate on the "embedding_binary" field.
func EmbeddingBinaryIn(vs ...[]byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldEmbeddingBinary, vs...))
}

// EmbeddingBinaryNotIn applies the NotIn predicate on the "embedding_binary" field.
func EmbeddingBinaryNotIn(vs ...[]byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldEmbeddingBinary, vs...))
}

// EmbeddingBinaryGT applies the GT predicate on the "embedding_binary" field.
func EmbeddingBinaryGT(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldEmbeddingBinary, v))
}

// EmbeddingBinaryGTE applies the GTE predicate on the "embedding_binary" field.
func EmbeddingBinaryGTE(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldEmbeddingBinary, v))
}

// EmbeddingBinaryLT applies the LT predicate on the "embedding_binary" field.
func EmbeddingBinaryLT(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldEmbeddingBinary, v))
}

// EmbeddingBinaryLTE applies the LTE predicate on the "embedding_binary" field.
func EmbeddingBinaryLTE(v []byte) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldEmbeddingBinary, v))
}

// EmbeddingBinaryIsNil applies the IsNil predicate on the "embedding_binary" field.
func EmbeddingBinaryIsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldEmbeddingBinary))
}

// EmbeddingBinaryNotNil applies the NotNil predicate on the "embedding_binary" field.
func EmbeddingBinaryNotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldEmbeddingBinary))
}

// HasDocument applies the HasEdge predicate on the "document" edge.
func HasDocument() predicate.Chunk {
	return predicate.Chunk(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DocumentTable, DocumentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentWith applies the HasEdge predicate on the "document" edge with a given conditions (other predicates).
func HasDocumentWith(preds ...predicate.Document) predicate.Chunk {
	return predicate.Chunk(func(s *sql.Selector) {
		step := newDocumentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.NotPredicates(p))
}
