// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/chunk"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/document"
	"github.com/rs/xid"
)

// Chunk is the model entity for the Chunk schema.
type Chunk struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// DocumentID holds the value of the "document_id" field.
	DocumentID xid.ID `json:"document_id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// EmbeddingModel holds the value of the "embedding_model" field.
	EmbeddingModel string `json:"embedding_model,omitempty"`
	// VectorID holds the value of the "vector_id" field.
	VectorID string `json:"vector_id,omitempty"`
	// EmbeddingInt8 holds the value of the "embedding_int8" field.
	EmbeddingInt8 []byte `json:"embedding_int8,omitempty"`
	// EmbeddingBinary holds the value of the "embedding_binary" field.
	EmbeddingBinary []byte `json:"embedding_binary,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChunkQuery when eager-loading is set.
	Edges        ChunkEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChunkEdges holds the relations/edges for other nodes in the graph.
type ChunkEdges struct {
	// Document holds the value of the document edge.
	Document *Document `json:"document,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DocumentOrErr returns the Document value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChunkEdges) DocumentOrErr() (*Document, error) {
	if e.Document != nil {
		return e.Document, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: document.Label}
	}
	return nil, &NotLoadedError{edge: "document"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Chunk) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chunk.FieldMetadata, chunk.FieldEmbeddingInt8, chunk.FieldEmbeddingBinary:
			values[i] = new([]byte)
		case chunk.FieldText, chunk.FieldEmbeddingModel, chunk.FieldVectorID:
			values[i] = new(sql.NullString)
		case chunk.FieldID, chunk.FieldDocumentID:
			values[i] = new(xid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Chunk fields.
func (_m *Chunk) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chunk.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case chunk.FieldDocumentID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field document_id", values[i])
			} else if value != nil {
				_m.DocumentID = *value
			}
		case chunk.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case chunk.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case chunk.FieldEmbeddingModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field embedding_model", values[i])
			} else if value.Valid {
				_m.EmbeddingModel = value.String
			}
		case chunk.FieldVectorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vector_id", values[i])
			} else if value.Valid {
				_m.VectorID = value.String
			}
		case chunk.FieldEmbeddingInt8:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field embedding_int8", values[i])
			} else if value != nil {
				_m.EmbeddingInt8 = *value
			}
		case chunk.FieldEmbeddingBinary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field embedding_binary", values[i])
			} else if value != nil {
				_m.EmbeddingBinary = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Chunk.
// This includes values selected through modifiers, order, etc.
func (_m *Chunk) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDocument queries the "document" edge of the Chunk entity.
func (_m *Chunk) QueryDocument() *DocumentQuery {
	return NewChunkClient(_m.config).QueryDocument(_m)
}

// Update returns a builder for updating this Chunk.
// Note that you need to call Chunk.Unwrap() before calling this method if this Chunk
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Chunk) Update() *ChunkUpdateOne {
	return NewChunkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Chunk entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Chunk) Unwrap() *Chunk {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Chunk is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Chunk) String() string {
	var builder strings.Builder
	builder.WriteString("Chunk(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("document_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DocumentID))
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("embedding_model=")
	builder.WriteString(_m.EmbeddingModel)
	builder.WriteString(", ")
	builder.WriteString("vector_id=")
	builder.WriteString(_m.VectorID)
	builder.WriteString(", ")
	builder.WriteString("embedding_int8=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmbeddingInt8))
	builder.WriteString(", ")
	builder.WriteString("embedding_binary=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmbeddingBinary))
	builder.WriteByte(')')
	return builder.String()
}

// Chunks is a parsable slice of Chunk.
type Chunks []*Chunk
