// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/chunk"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/document"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/predicate"
	"github.com/rs/xid"
)

// ChunkUpdate is the builder for updating Chunk entities.
type ChunkUpdate struct {
	config
	hooks    []Hook
	mutation *ChunkMutation
}

// Where appends a list predicates to the ChunkUpdate builder.
func (_u *ChunkUpdate) Where(ps ...predicate.Chunk) *ChunkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDocumentID sets the "document_id" field.
func (_u *ChunkUpdate) SetDocumentID(v xid.ID) *ChunkUpdate {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableDocumentID(v *xid.ID) *ChunkUpdate {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetText sets the "text" field.
func (_u *ChunkUpdate) SetText(v string) *ChunkUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableText(v *string) *ChunkUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ChunkUpdate) SetMetadata(v map[string]interface{}) *ChunkUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ChunkUpdate) ClearMetadata() *ChunkUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_u *ChunkUpdate) SetEmbeddingModel(v string) *ChunkUpdate {
	_u.mutation.SetEmbeddingModel(v)
	return _u
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableEmbeddingModel(v *string) *ChunkUpdate {
	if v != nil {
		_u.SetEmbeddingModel(*v)
	}
	return _u
}

// ClearEmbeddingModel clears the value of the "embedding_model" field.
func (_u *ChunkUpdate) ClearEmbeddingModel() *ChunkUpdate {
	_u.mutation.ClearEmbeddingModel()
	return _u
}

// SetVectorID sets the "vector_id" field.
func (_u *ChunkUpdate) SetVectorID(v string) *ChunkUpdate {
	_u.mutation.SetVectorID(v)
	return _u
}

// SetNillableVectorID sets the "vector_id" field if the given value is not nil.
func (_u *ChunkUpdate) SetNillableVectorID(v *string) *ChunkUpdate {
	if v != nil {
		_u.SetVectorID(*v)
	}
	return _u
}

// ClearVectorID clears the value of the "vector_id" field.
func (_u *ChunkUpdate) ClearVectorID() *ChunkUpdate {
	_u.mutation.ClearVectorID()
	return _u
}

// SetEmbeddingInt8 sets the "embedding_int8" field.
func (_u *ChunkUpdate) SetEmbeddingInt8(v []byte) *ChunkUpdate {
	_u.mutation.SetEmbeddingInt8(v)
	return _u
}

// ClearEmbeddingInt8 clears the value of the "embedding_int8" field.
func (_u *ChunkUpdate) ClearEmbeddingInt8() *ChunkUpdate {
	_u.mutation.ClearEmbeddingInt8()
	return _u
}

// SetEmbeddingBinary sets the "embedding_binary" field.
func (_u *ChunkUpdate) SetEmbeddingBinary(v []byte) *ChunkUpdate {
	_u.mutation.SetEmbeddingBinary(v)
	return _u
}

// ClearEmbeddingBinary clears the value of the "embedding_binary" field.
func (_u *ChunkUpdate) ClearEmbeddingBinary() *ChunkUpdate {
	_u.mutation.ClearEmbeddingBinary()
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *ChunkUpdate) SetDocument(v *Document) *ChunkUpdate {
	return _u.SetDocumentID(v.ID)
}

// Mutation returns the ChunkMutation object of the builder.
func (_u *ChunkUpdate) Mutation() *ChunkMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *ChunkUpdate) ClearDocument() *ChunkUpdate {
	_u.mutation.ClearDocument()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChunkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChunkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChunkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChunkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChunkUpdate) check() error {
	if v, ok := _u.mutation.Text(); ok {
		if err := chunk.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Chunk.text": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Chunk.document"`)
	}
	return nil
}

func (_u *ChunkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chunk.Table, chunk.Columns, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(chunk.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(chunk.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(chunk.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.EmbeddingModel(); ok {
		_spec.SetField(chunk.FieldEmbeddingModel, field.TypeString, value)
	}
	if _u.mutation.EmbeddingModelCleared() {
		_spec.ClearField(chunk.FieldEmbeddingModel, field.TypeString)
	}
	if value, ok := _u.mutation.VectorID(); ok {
		_spec.SetField(chunk.FieldVectorID, field.TypeString, value)
	}
	if _u.mutation.VectorIDCleared() {
		_spec.ClearField(chunk.FieldVectorID, field.TypeString)
	}
	if value, ok := _u.mutation.EmbeddingInt8(); ok {
		_spec.SetField(chunk.FieldEmbeddingInt8, field.TypeBytes, value)
	}
	if _u.mutation.EmbeddingInt8Cleared() {
		_spec.ClearField(chunk.FieldEmbeddingInt8, field.TypeBytes)
	}
	if value, ok := _u.mutation.EmbeddingBinary(); ok {
		_spec.SetField(chunk.FieldEmbeddingBinary, field.TypeBytes, value)
	}
	if _u.mutation.EmbeddingBinaryCleared() {
		_spec.ClearField(chunk.FieldEmbeddingBinary, field.TypeBytes)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chunk.DocumentTable,
			Columns: []string{chunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chunk.DocumentTable,
			Columns: []string{chunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChunkUpdateOne is the builder for updating a single Chunk entity.
type ChunkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChunkMutation
}

// SetDocumentID sets the "document_id" field.
func (_u *ChunkUpdateOne) SetDocumentID(v xid.ID) *ChunkUpdateOne {
	_u.mutation.SetDocumentID(v)
	return _u
}

// SetNillableDocumentID sets the "document_id" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableDocumentID(v *xid.ID) *ChunkUpdateOne {
	if v != nil {
		_u.SetDocumentID(*v)
	}
	return _u
}

// SetText sets the "text" field.
func (_u *ChunkUpdateOne) SetText(v string) *ChunkUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableText(v *string) *ChunkUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ChunkUpdateOne) SetMetadata(v map[string]interface{}) *ChunkUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ChunkUpdateOne) ClearMetadata() *ChunkUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_u *ChunkUpdateOne) SetEmbeddingModel(v string) *ChunkUpdateOne {
	_u.mutation.SetEmbeddingModel(v)
	return _u
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableEmbeddingModel(v *string) *ChunkUpdateOne {
	if v != nil {
		_u.SetEmbeddingModel(*v)
	}
	return _u
}

// ClearEmbeddingModel clears the value of the "embedding_model" field.
func (_u *ChunkUpdateOne) ClearEmbeddingModel() *ChunkUpdateOne {
	_u.mutation.ClearEmbeddingModel()
	return _u
}

// SetVectorID sets the "vector_id" field.
func (_u *ChunkUpdateOne) SetVectorID(v string) *ChunkUpdateOne {
	_u.mutation.SetVectorID(v)
	return _u
}

// SetNillableVectorID sets the "vector_id" field if the given value is not nil.
func (_u *ChunkUpdateOne) SetNillableVectorID(v *string) *ChunkUpdateOne {
	if v != nil {
		_u.SetVectorID(*v)
	}
	return _u
}

// ClearVectorID clears the value of the "vector_id" field.
func (_u *ChunkUpdateOne) ClearVectorID() *ChunkUpdateOne {
	_u.mutation.ClearVectorID()
	return _u
}

// SetEmbeddingInt8 sets the "embedding_int8" field.
func (_u *ChunkUpdateOne) SetEmbeddingInt8(v []byte) *ChunkUpdateOne {
	_u.mutation.SetEmbeddingInt8(v)
	return _u
}

// ClearEmbeddingInt8 clears the value of the "embedding_int8" field.
func (_u *ChunkUpdateOne) ClearEmbeddingInt8() *ChunkUpdateOne {
	_u.mutation.ClearEmbeddingInt8()
	return _u
}

// SetEmbeddingBinary sets the "embedding_binary" field.
func (_u *ChunkUpdateOne) SetEmbeddingBinary(v []byte) *ChunkUpdateOne {
	_u.mutation.SetEmbeddingBinary(v)
	return _u
}

// ClearEmbeddingBinary clears the value of the "embedding_binary" field.
func (_u *ChunkUpdateOne) ClearEmbeddingBinary() *ChunkUpdateOne {
	_u.mutation.ClearEmbeddingBinary()
	return _u
}

// SetDocument sets the "document" edge to the Document entity.
func (_u *ChunkUpdateOne) SetDocument(v *Document) *ChunkUpdateOne {
	return _u.SetDocumentID(v.ID)
}

// Mutation returns the ChunkMutation object of the builder.
func (_u *ChunkUpdateOne) Mutation() *ChunkMutation {
	return _u.mutation
}

// ClearDocument clears the "document" edge to the Document entity.
func (_u *ChunkUpdateOne) ClearDocument() *ChunkUpdateOne {
	_u.mutation.ClearDocument()
	return _u
}

// Where appends a list predicates to the ChunkUpdate builder.
func (_u *ChunkUpdateOne) Where(ps ...predicate.Chunk) *ChunkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChunkUpdateOne) Select(field string, fields ...string) *ChunkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Chunk entity.
func (_u *ChunkUpdateOne) Save(ctx context.Context) (*Chunk, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChunkUpdateOne) SaveX(ctx context.Context) *Chunk {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChunkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChunkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChunkUpdateOne) check() error {
	if v, ok := _u.mutation.Text(); ok {
		if err := chunk.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Chunk.text": %w`, err)}
		}
	}
	if _u.mutation.DocumentCleared() && len(_u.mutation.DocumentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Chunk.document"`)
	}
	return nil
}

func (_u *ChunkUpdateOne) sqlSave(ctx context.Context) (_node *Chunk, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chunk.Table, chunk.Columns, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chunk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chunk.FieldID)
		for _, f := range fields {
			if !chunk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chunk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(chunk.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(chunk.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(chunk.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.EmbeddingModel(); ok {
		_spec.SetField(chunk.FieldEmbeddingModel, field.TypeString, value)
	}
	if _u.mutation.EmbeddingModelCleared() {
		_spec.ClearField(chunk.FieldEmbeddingModel, field.TypeString)
	}
	if value, ok := _u.mutation.VectorID(); ok {
		_spec.SetField(chunk.FieldVectorID, field.TypeString, value)
	}
	if _u.mutation.VectorIDCleared() {
		_spec.ClearField(chunk.FieldVectorID, field.TypeString)
	}
	if value, ok := _u.mutation.EmbeddingInt8(); ok {
		_spec.SetField(chunk.FieldEmbeddingInt8, field.TypeBytes, value)
	}
	if _u.mutation.EmbeddingInt8Cleared() {
		_spec.ClearField(chunk.FieldEmbeddingInt8, field.TypeBytes)
	}
	if value, ok := _u.mutation.EmbeddingBinary(); ok {
		_spec.SetField(chunk.FieldEmbeddingBinary, field.TypeBytes, value)
	}
	if _u.mutation.EmbeddingBinaryCleared() {
		_spec.ClearField(chunk.FieldEmbeddingBinary, field.TypeBytes)
	}
	if _u.mutation.DocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chunk.DocumentTable,
			Columns: []string{chunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chunk.DocumentTable,
			Columns: []string{chunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Chunk{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
