// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/chunk"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/document"
	"github.com/rs/xid"
)

// ChunkCreate is the builder for creating a Chunk entity.
type ChunkCreate struct {
	config
	mutation *ChunkMutation
	hooks    []Hook
}

// SetDocumentID sets the "document_id" field.
func (_c *ChunkCreate) SetDocumentID(v xid.ID) *ChunkCreate {
	_c.mutation.SetDocumentID(v)
	return _c
}

// SetText sets the "text" field.
func (_c *ChunkCreate) SetText(v string) *ChunkCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ChunkCreate) SetMetadata(v map[string]interface{}) *ChunkCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_c *ChunkCreate) SetEmbeddingModel(v string) *ChunkCreate {
	_c.mutation.SetEmbeddingModel(v)
	return _c
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableEmbeddingModel(v *string) *ChunkCreate {
	if v != nil {
		_c.SetEmbeddingModel(*v)
	}
	return _c
}

// SetVectorID sets the "vector_id" field.
func (_c *ChunkCreate) SetVectorID(v string) *ChunkCreate {
	_c.mutation.SetVectorID(v)
	return _c
}

// SetNillableVectorID sets the "vector_id" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableVectorID(v *string) *ChunkCreate {
	if v != nil {
		_c.SetVectorID(*v)
	}
	return _c
}

// SetEmbeddingInt8 sets the "embedding_int8" field.
func (_c *ChunkCreate) SetEmbeddingInt8(v []byte) *ChunkCreate {
	_c.mutation.SetEmbeddingInt8(v)
	return _c
}

// SetEmbeddingBinary sets the "embedding_binary" field.
func (_c *ChunkCreate) SetEmbeddingBinary(v []byte) *ChunkCreate {
	_c.mutation.SetEmbeddingBinary(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ChunkCreate) SetID(v xid.ID) *ChunkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableID(v *xid.ID) *ChunkCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDocument sets the "document" edge to the Document entity.
func (_c *ChunkCreate) SetDocument(v *Document) *ChunkCreate {
	return _c.SetDocumentID(v.ID)
}

// Mutation returns the ChunkMutation object of the builder.
func (_c *ChunkCreate) Mutation() *ChunkMutation {
	return _c.mutation
}

// Save creates the Chunk in the database.
func (_c *ChunkCreate) Save(ctx context.Context) (*Chunk, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChunkCreate) SaveX(ctx context.Context) *Chunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChunkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChunkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChunkCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := chunk.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChunkCreate) check() error {
	if _, ok := _c.mutation.DocumentID(); !ok {
		return &ValidationError{Name: "document_id", err: errors.New(`ent: missing required field "Chunk.document_id"`)}
	}
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Chunk.text"`)}
	}
	if v, ok := _c.mutation.Text(); ok {
		if err := chunk.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Chunk.text": %w`, err)}
		}
	}
	if len(_c.mutation.DocumentIDs()) == 0 {
		return &ValidationError{Name: "document", err: errors.New(`ent: missing required edge "Chunk.document"`)}
	}
	return nil
}

func (_c *ChunkCreate) sqlSave(ctx context.Context) (*Chunk, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChunkCreate) createSpec() (*Chunk, *sqlgraph.CreateSpec) {
	var (
		_node = &Chunk{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chunk.Table, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(chunk.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(chunk.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.EmbeddingModel(); ok {
		_spec.SetField(chunk.FieldEmbeddingModel, field.TypeString, value)
		_node.EmbeddingModel = value
	}
	if value, ok := _c.mutation.VectorID(); ok {
		_spec.SetField(chunk.FieldVectorID, field.TypeString, value)
		_node.VectorID = value
	}
	if value, ok := _c.mutation.EmbeddingInt8(); ok {
		_spec.SetField(chunk.FieldEmbeddingInt8, field.TypeBytes, value)
		_node.EmbeddingInt8 = value
	}
	if value, ok := _c.mutation.EmbeddingBinary(); ok {
		_spec.SetField(chunk.FieldEmbeddingBinary, field.TypeBytes, value)
		_node.EmbeddingBinary = value
	}
	if nodes := _c.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chunk.DocumentTable,
			Columns: []string{chunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DocumentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChunkCreateBulk is the builder for creating many Chunk entities in bulk.
type ChunkCreateBulk struct {
	config
	err      error
	builders []*ChunkCreate
}

// Save creates the Chunk entities in the database.
func (_c *ChunkCreateBulk) Save(ctx context.Context) ([]*Chunk, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Chunk, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChunkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChunkCreateBulk) SaveX(ctx context.Context) []*Chunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChunkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChunkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
