// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/chunk"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/document"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/predicate"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/tenant"
	"github.com/rs/xid"
)

// DocumentUpdate is the builder for updating Document entities.
type DocumentUpdate struct {
	config
	hooks    []Hook
	mutation *DocumentMutation
}

// Where appends a list predicates to the DocumentUpdate builder.
func (_u *DocumentUpdate) Where(ps ...predicate.Document) *DocumentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *DocumentUpdate) SetTenantID(v xid.ID) *DocumentUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableTenantID(v *xid.ID) *DocumentUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DocumentUpdate) SetTitle(v string) *DocumentUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableTitle(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *DocumentUpdate) SetSourceURL(v string) *DocumentUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableSourceURL(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *DocumentUpdate) ClearSourceURL() *DocumentUpdate {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DocumentUpdate) SetMetadata(v map[string]interface{}) *DocumentUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *DocumentUpdate) ClearMetadata() *DocumentUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetNormalizedHash sets the "normalized_hash" field.
func (_u *DocumentUpdate) SetNormalizedHash(v string) *DocumentUpdate {
	_u.mutation.SetNormalizedHash(v)
	return _u
}

// SetNillableNormalizedHash sets the "normalized_hash" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableNormalizedHash(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetNormalizedHash(*v)
	}
	return _u
}

// ClearNormalizedHash clears the value of the "normalized_hash" field.
func (_u *DocumentUpdate) ClearNormalizedHash() *DocumentUpdate {
	_u.mutation.ClearNormalizedHash()
	return _u
}

// SetDocType sets the "doc_type" field.
func (_u *DocumentUpdate) SetDocType(v string) *DocumentUpdate {
	_u.mutation.SetDocType(v)
	return _u
}

// SetNillableDocType sets the "doc_type" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableDocType(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetDocType(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *DocumentUpdate) SetContentType(v string) *DocumentUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableContentType(v *string) *DocumentUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// ClearContentType clears the value of the "content_type" field.
func (_u *DocumentUpdate) ClearContentType() *DocumentUpdate {
	_u.mutation.ClearContentType()
	return _u
}

// SetSize sets the "size" field.
func (_u *DocumentUpdate) SetSize(v int64) *DocumentUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableSize(v *int64) *DocumentUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *DocumentUpdate) AddSize(v int64) *DocumentUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *DocumentUpdate) ClearSize() *DocumentUpdate {
	_u.mutation.ClearSize()
	return _u
}

// SetDuplicateOf sets the "duplicate_of" field.
func (_u *DocumentUpdate) SetDuplicateOf(v xid.ID) *DocumentUpdate {
	_u.mutation.SetDuplicateOf(v)
	return _u
}

// SetNillableDuplicateOf sets the "duplicate_of" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableDuplicateOf(v *xid.ID) *DocumentUpdate {
	if v != nil {
		_u.SetDuplicateOf(*v)
	}
	return _u
}

// ClearDuplicateOf clears the value of the "duplicate_of" field.
func (_u *DocumentUpdate) ClearDuplicateOf() *DocumentUpdate {
	_u.mutation.ClearDuplicateOf()
	return _u
}

// SetHasPii sets the "has_pii" field.
func (_u *DocumentUpdate) SetHasPii(v bool) *DocumentUpdate {
	_u.mutation.SetHasPii(v)
	return _u
}

// SetNillableHasPii sets the "has_pii" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableHasPii(v *bool) *DocumentUpdate {
	if v != nil {
		_u.SetHasPii(*v)
	}
	return _u
}

// SetPiiSummary sets the "pii_summary" field.
func (_u *DocumentUpdate) SetPiiSummary(v map[string]interface{}) *DocumentUpdate {
	_u.mutation.SetPiiSummary(v)
	return _u
}

// ClearPiiSummary clears the value of the "pii_summary" field.
func (_u *DocumentUpdate) ClearPiiSummary() *DocumentUpdate {
	_u.mutation.ClearPiiSummary()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DocumentUpdate) SetCreatedAt(v time.Time) *DocumentUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DocumentUpdate) SetNillableCreatedAt(v *time.Time) *DocumentUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *DocumentUpdate) SetTenant(v *Tenant) *DocumentUpdate {
	return _u.SetTenantID(v.ID)
}

// AddChunkIDs adds the "chunks" edge to the Chunk entity by IDs.
func (_u *DocumentUpdate) AddChunkIDs(ids ...xid.ID) *DocumentUpdate {
	_u.mutation.AddChunkIDs(ids...)
	return _u
}

// AddChunks adds the "chunks" edges to the Chunk entity.
func (_u *DocumentUpdate) AddChunks(v ...*Chunk) *DocumentUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChunkIDs(ids...)
}

// Mutation returns the DocumentMutation object of the builder.
func (_u *DocumentUpdate) Mutation() *DocumentMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *DocumentUpdate) ClearTenant() *DocumentUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearChunks clears all "chunks" edges to the Chunk entity.
func (_u *DocumentUpdate) ClearChunks() *DocumentUpdate {
	_u.mutation.ClearChunks()
	return _u
}

// RemoveChunkIDs removes the "chunks" edge to Chunk entities by IDs.
func (_u *DocumentUpdate) RemoveChunkIDs(ids ...xid.ID) *DocumentUpdate {
	_u.mutation.RemoveChunkIDs(ids...)
	return _u
}

// RemoveChunks removes "chunks" edges to Chunk entities.
func (_u *DocumentUpdate) RemoveChunks(v ...*Chunk) *DocumentUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChunkIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DocumentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DocumentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Document.tenant"`)
	}
	return nil
}

func (_u *DocumentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(document.Table, document.Columns, sqlgraph.NewFieldSpec(document.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(document.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(document.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(document.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(document.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(document.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.NormalizedHash(); ok {
		_spec.SetField(document.FieldNormalizedHash, field.TypeString, value)
	}
	if _u.mutation.NormalizedHashCleared() {
		_spec.ClearField(document.FieldNormalizedHash, field.TypeString)
	}
	if value, ok := _u.mutation.DocType(); ok {
		_spec.SetField(document.FieldDocType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(document.FieldContentType, field.TypeString, value)
	}
	if _u.mutation.ContentTypeCleared() {
		_spec.ClearField(document.FieldContentType, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(document.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(document.FieldSize, field.TypeInt64, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(document.FieldSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.DuplicateOf(); ok {
		_spec.SetField(document.FieldDuplicateOf, field.TypeString, value)
	}
	if _u.mutation.DuplicateOfCleared() {
		_spec.ClearField(document.FieldDuplicateOf, field.TypeString)
	}
	if value, ok := _u.mutation.HasPii(); ok {
		_spec.SetField(document.FieldHasPii, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PiiSummary(); ok {
		_spec.SetField(document.FieldPiiSummary, field.TypeJSON, value)
	}
	if _u.mutation.PiiSummaryCleared() {
		_spec.ClearField(document.FieldPiiSummary, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(document.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.TenantTable,
			Columns: []string{document.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.TenantTable,
			Columns: []string{document.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.ChunksTable,
			Columns: []string{document.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChunksIDs(); len(nodes) > 0 && !_u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.ChunksTable,
			Columns: []string{document.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChunksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.ChunksTable,
			Columns: []string{document.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{document.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DocumentUpdateOne is the builder for updating a single Document entity.
type DocumentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DocumentMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *DocumentUpdateOne) SetTenantID(v xid.ID) *DocumentUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableTenantID(v *xid.ID) *DocumentUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DocumentUpdateOne) SetTitle(v string) *DocumentUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableTitle(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *DocumentUpdateOne) SetSourceURL(v string) *DocumentUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableSourceURL(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *DocumentUpdateOne) ClearSourceURL() *DocumentUpdateOne {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DocumentUpdateOne) SetMetadata(v map[string]interface{}) *DocumentUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *DocumentUpdateOne) ClearMetadata() *DocumentUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetNormalizedHash sets the "normalized_hash" field.
func (_u *DocumentUpdateOne) SetNormalizedHash(v string) *DocumentUpdateOne {
	_u.mutation.SetNormalizedHash(v)
	return _u
}

// SetNillableNormalizedHash sets the "normalized_hash" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableNormalizedHash(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetNormalizedHash(*v)
	}
	return _u
}

// ClearNormalizedHash clears the value of the "normalized_hash" field.
func (_u *DocumentUpdateOne) ClearNormalizedHash() *DocumentUpdateOne {
	_u.mutation.ClearNormalizedHash()
	return _u
}

// SetDocType sets the "doc_type" field.
func (_u *DocumentUpdateOne) SetDocType(v string) *DocumentUpdateOne {
	_u.mutation.SetDocType(v)
	return _u
}

// SetNillableDocType sets the "doc_type" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableDocType(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetDocType(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *DocumentUpdateOne) SetContentType(v string) *DocumentUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableContentType(v *string) *DocumentUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// ClearContentType clears the value of the "content_type" field.
func (_u *DocumentUpdateOne) ClearContentType() *DocumentUpdateOne {
	_u.mutation.ClearContentType()
	return _u
}

// SetSize sets the "size" field.
func (_u *DocumentUpdateOne) SetSize(v int64) *DocumentUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableSize(v *int64) *DocumentUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *DocumentUpdateOne) AddSize(v int64) *DocumentUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *DocumentUpdateOne) ClearSize() *DocumentUpdateOne {
	_u.mutation.ClearSize()
	return _u
}

// SetDuplicateOf sets the "duplicate_of" field.
func (_u *DocumentUpdateOne) SetDuplicateOf(v xid.ID) *DocumentUpdateOne {
	_u.mutation.SetDuplicateOf(v)
	return _u
}

// SetNillableDuplicateOf sets the "duplicate_of" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableDuplicateOf(v *xid.ID) *DocumentUpdateOne {
	if v != nil {
		_u.SetDuplicateOf(*v)
	}
	return _u
}

// ClearDuplicateOf clears the value of the "duplicate_of" field.
func (_u *DocumentUpdateOne) ClearDuplicateOf() *DocumentUpdateOne {
	_u.mutation.ClearDuplicateOf()
	return _u
}

// SetHasPii sets the "has_pii" field.
func (_u *DocumentUpdateOne) SetHasPii(v bool) *DocumentUpdateOne {
	_u.mutation.SetHasPii(v)
	return _u
}

// SetNillableHasPii sets the "has_pii" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableHasPii(v *bool) *DocumentUpdateOne {
	if v != nil {
		_u.SetHasPii(*v)
	}
	return _u
}

// SetPiiSummary sets the "pii_summary" field.
func (_u *DocumentUpdateOne) SetPiiSummary(v map[string]interface{}) *DocumentUpdateOne {
	_u.mutation.SetPiiSummary(v)
	return _u
}

// ClearPiiSummary clears the value of the "pii_summary" field.
func (_u *DocumentUpdateOne) ClearPiiSummary() *DocumentUpdateOne {
	_u.mutation.ClearPiiSummary()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DocumentUpdateOne) SetCreatedAt(v time.Time) *DocumentUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DocumentUpdateOne) SetNillableCreatedAt(v *time.Time) *DocumentUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *DocumentUpdateOne) SetTenant(v *Tenant) *DocumentUpdateOne {
	return _u.SetTenantID(v.ID)
}

// AddChunkIDs adds the "chunks" edge to the Chunk entity by IDs.
func (_u *DocumentUpdateOne) AddChunkIDs(ids ...xid.ID) *DocumentUpdateOne {
	_u.mutation.AddChunkIDs(ids...)
	return _u
}

// AddChunks adds the "chunks" edges to the Chunk entity.
func (_u *DocumentUpdateOne) AddChunks(v ...*Chunk) *DocumentUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChunkIDs(ids...)
}

// Mutation returns the DocumentMutation object of the builder.
func (_u *DocumentUpdateOne) Mutation() *DocumentMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *DocumentUpdateOne) ClearTenant() *DocumentUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearChunks clears all "chunks" edges to the Chunk entity.
func (_u *DocumentUpdateOne) ClearChunks() *DocumentUpdateOne {
	_u.mutation.ClearChunks()
	return _u
}

// RemoveChunkIDs removes the "chunks" edge to Chunk entities by IDs.
func (_u *DocumentUpdateOne) RemoveChunkIDs(ids ...xid.ID) *DocumentUpdateOne {
	_u.mutation.RemoveChunkIDs(ids...)
	return _u
}

// RemoveChunks removes "chunks" edges to Chunk entities.
func (_u *DocumentUpdateOne) RemoveChunks(v ...*Chunk) *DocumentUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChunkIDs(ids...)
}

// Where appends a list predicates to the DocumentUpdate builder.
func (_u *DocumentUpdateOne) Where(ps ...predicate.Document) *DocumentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DocumentUpdateOne) Select(field string, fields ...string) *DocumentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Document entity.
func (_u *DocumentUpdateOne) Save(ctx context.Context) (*Document, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DocumentUpdateOne) SaveX(ctx context.Context) *Document {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DocumentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DocumentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DocumentUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Document.tenant"`)
	}
	return nil
}

func (_u *DocumentUpdateOne) sqlSave(ctx context.Context) (_node *Document, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(document.Table, document.Columns, sqlgraph.NewFieldSpec(document.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Document.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, document.FieldID)
		for _, f := range fields {
			if !document.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != document.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(document.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(document.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(document.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(document.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(document.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.NormalizedHash(); ok {
		_spec.SetField(document.FieldNormalizedHash, field.TypeString, value)
	}
	if _u.mutation.NormalizedHashCleared() {
		_spec.ClearField(document.FieldNormalizedHash, field.TypeString)
	}
	if value, ok := _u.mutation.DocType(); ok {
		_spec.SetField(document.FieldDocType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(document.FieldContentType, field.TypeString, value)
	}
	if _u.mutation.ContentTypeCleared() {
		_spec.ClearField(document.FieldContentType, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(document.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(document.FieldSize, field.TypeInt64, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(document.FieldSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.DuplicateOf(); ok {
		_spec.SetField(document.FieldDuplicateOf, field.TypeString, value)
	}
	if _u.mutation.DuplicateOfCleared() {
		_spec.ClearField(document.FieldDuplicateOf, field.TypeString)
	}
	if value, ok := _u.mutation.HasPii(); ok {
		_spec.SetField(document.FieldHasPii, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PiiSummary(); ok {
		_spec.SetField(document.FieldPiiSummary, field.TypeJSON, value)
	}
	if _u.mutation.PiiSummaryCleared() {
		_spec.ClearField(document.FieldPiiSummary, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(document.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.TenantTable,
			Columns: []string{document.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.TenantTable,
			Columns: []string{document.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.ChunksTable,
			Columns: []string{document.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChunksIDs(); len(nodes) > 0 && !_u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.ChunksTable,
			Columns: []string{document.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChunksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.ChunksTable,
			Columns: []string{document.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Document{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{document.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
