// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/chunk"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/document"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/tenant"
	"github.com/rs/xid"
)

// DocumentCreate is the builder for creating a Document entity.
type DocumentCreate struct {
	config
	mutation *DocumentMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *DocumentCreate) SetTenantID(v xid.ID) *DocumentCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *DocumentCreate) SetTitle(v string) *DocumentCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *DocumentCreate) SetSourceURL(v string) *DocumentCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableSourceURL(v *string) *DocumentCreate {
	if v != nil {
		_c.SetSourceURL(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *DocumentCreate) SetMetadata(v map[string]interface{}) *DocumentCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetNormalizedHash sets the "normalized_hash" field.
func (_c *DocumentCreate) SetNormalizedHash(v string) *DocumentCreate {
	_c.mutation.SetNormalizedHash(v)
	return _c
}

// SetNillableNormalizedHash sets the "normalized_hash" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableNormalizedHash(v *string) *DocumentCreate {
	if v != nil {
		_c.SetNormalizedHash(*v)
	}
	return _c
}

// SetDocType sets the "doc_type" field.
func (_c *DocumentCreate) SetDocType(v string) *DocumentCreate {
	_c.mutation.SetDocType(v)
	return _c
}

// SetNillableDocType sets the "doc_type" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableDocType(v *string) *DocumentCreate {
	if v != nil {
		_c.SetDocType(*v)
	}
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *DocumentCreate) SetContentType(v string) *DocumentCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableContentType(v *string) *DocumentCreate {
	if v != nil {
		_c.SetContentType(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *DocumentCreate) SetSize(v int64) *DocumentCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableSize(v *int64) *DocumentCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetDuplicateOf sets the "duplicate_of" field.
func (_c *DocumentCreate) SetDuplicateOf(v xid.ID) *DocumentCreate {
	_c.mutation.SetDuplicateOf(v)
	return _c
}

// SetNillableDuplicateOf sets the "duplicate_of" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableDuplicateOf(v *xid.ID) *DocumentCreate {
	if v != nil {
		_c.SetDuplicateOf(*v)
	}
	return _c
}

// SetHasPii sets the "has_pii" field.
func (_c *DocumentCreate) SetHasPii(v bool) *DocumentCreate {
	_c.mutation.SetHasPii(v)
	return _c
}

// SetNillableHasPii sets the "has_pii" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableHasPii(v *bool) *DocumentCreate {
	if v != nil {
		_c.SetHasPii(*v)
	}
	return _c
}

// SetPiiSummary sets the "pii_summary" field.
func (_c *DocumentCreate) SetPiiSummary(v map[string]interface{}) *DocumentCreate {
	_c.mutation.SetPiiSummary(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocumentCreate) SetCreatedAt(v time.Time) *DocumentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableCreatedAt(v *time.Time) *DocumentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DocumentCreate) SetID(v xid.ID) *DocumentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableID(v *xid.ID) *DocumentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *DocumentCreate) SetTenant(v *Tenant) *DocumentCreate {
	return _c.SetTenantID(v.ID)
}

// AddChunkIDs adds the "chunks" edge to the Chunk entity by IDs.
func (_c *DocumentCreate) AddChunkIDs(ids ...xid.ID) *DocumentCreate {
	_c.mutation.AddChunkIDs(ids...)
	return _c
}

// AddChunks adds the "chunks" edges to the Chunk entity.
func (_c *DocumentCreate) AddChunks(v ...*Chunk) *DocumentCreate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChunkIDs(ids...)
}

// Mutation returns the DocumentMutation object of the builder.
func (_c *DocumentCreate) Mutation() *DocumentMutation {
	return _c.mutation
}

// Save creates the Document in the database.
func (_c *DocumentCreate) Save(ctx context.Context) (*Document, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentCreate) SaveX(ctx context.Context) *Document {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentCreate) defaults() {
	if _, ok := _c.mutation.DocType(); !ok {
		v := document.DefaultDocType
		_c.mutation.SetDocType(v)
	}
	if _, ok := _c.mutation.HasPii(); !ok {
		v := document.DefaultHasPii
		_c.mutation.SetHasPii(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := document.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := document.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Document.tenant_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Document.title"`)}
	}
	if _, ok := _c.mutation.DocType(); !ok {
		return &ValidationError{Name: "doc_type", err: errors.New(`ent: missing required field "Document.doc_type"`)}
	}
	if _, ok := _c.mutation.HasPii(); !ok {
		return &ValidationError{Name: "has_pii", err: errors.New(`ent: missing required field "Document.has_pii"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Document.created_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Document.tenant"`)}
	}
	return nil
}

func (_c *DocumentCreate) sqlSave(ctx context.Context) (*Document, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentCreate) createSpec() (*Document, *sqlgraph.CreateSpec) {
	var (
		_node = &Document{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(document.Table, sqlgraph.NewFieldSpec(document.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(document.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(document.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(document.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.NormalizedHash(); ok {
		_spec.SetField(document.FieldNormalizedHash, field.TypeString, value)
		_node.NormalizedHash = &value
	}
	if value, ok := _c.mutation.DocType(); ok {
		_spec.SetField(document.FieldDocType, field.TypeString, value)
		_node.DocType = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(document.FieldContentType, field.TypeString, value)
		_node.ContentType = &value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(document.FieldSize, field.TypeInt64, value)
		_node.Size = &value
	}
	if value, ok := _c.mutation.DuplicateOf(); ok {
		_spec.SetField(document.FieldDuplicateOf, field.TypeString, value)
		_node.DuplicateOf = &value
	}
	if value, ok := _c.mutation.HasPii(); ok {
		_spec.SetField(document.FieldHasPii, field.TypeBool, value)
		_node.HasPii = value
	}
	if value, ok := _c.mutation.PiiSummary(); ok {
		_spec.SetField(document.FieldPiiSummary, field.TypeJSON, value)
		_node.PiiSummary = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(document.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.TenantTable,
			Columns: []string{document.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChunksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.ChunksTable,
			Columns: []string{document.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DocumentCreateBulk is the builder for creating many Document entities in bulk.
type DocumentCreateBulk struct {
	config
	err      error
	builders []*DocumentCreate
}

// Save creates the Document entities in the database.
func (_c *DocumentCreateBulk) Save(ctx context.Context) ([]*Document, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Document, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentCreateBulk) SaveX(ctx context.Context) []*Document {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
