// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/document"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/tenant"
	"github.com/rs/xid"
)

// Document is the model entity for the Document schema.
type Document struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID xid.ID `json:"tenant_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// SourceURL holds the value of the "source_url" field.
	SourceURL string `json:"source_url,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// NormalizedHash holds the value of the "normalized_hash" field.
	NormalizedHash *string `json:"normalized_hash,omitempty"`
	// DocType holds the value of the "doc_type" field.
	DocType string `json:"doc_type,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType *string `json:"content_type,omitempty"`
	// Size holds the value of the "size" field.
	Size *int64 `json:"size,omitempty"`
	// DuplicateOf holds the value of the "duplicate_of" field.
	DuplicateOf *xid.ID `json:"duplicate_of,omitempty"`
	// HasPii holds the value of the "has_pii" field.
	HasPii bool `json:"has_pii,omitempty"`
	// PiiSummary holds the value of the "pii_summary" field.
	PiiSummary map[string]interface{} `json:"pii_summary,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DocumentQuery when eager-loading is set.
	Edges        DocumentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DocumentEdges holds the relations/edges for other nodes in the graph.
type DocumentEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Chunks holds the value of the chunks edge.
	Chunks []*Chunk `json:"chunks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DocumentEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// ChunksOrErr returns the Chunks value or an error if the edge
// was not loaded in eager-loading.
func (e DocumentEdges) ChunksOrErr() ([]*Chunk, error) {
	if e.loadedTypes[1] {
		return e.Chunks, nil
	}
	return nil, &NotLoadedError{edge: "chunks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Document) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case document.FieldDuplicateOf:
			values[i] = &sql.NullScanner{S: new(xid.ID)}
		case document.FieldMetadata, document.FieldPiiSummary:
			values[i] = new([]byte)
		case document.FieldHasPii:
			values[i] = new(sql.NullBool)
		case document.FieldSize:
			values[i] = new(sql.NullInt64)
		case document.FieldTitle, document.FieldSourceURL, document.FieldNormalizedHash, document.FieldDocType, document.FieldContentType:
			values[i] = new(sql.NullString)
		case document.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case document.FieldID, document.FieldTenantID:
			values[i] = new(xid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Document fields.
func (_m *Document) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case document.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case document.FieldTenantID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case document.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case document.FieldSourceURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_url", values[i])
			} else if value.Valid {
				_m.SourceURL = value.String
			}
		case document.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case document.FieldNormalizedHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_hash", values[i])
			} else if value.Valid {
				_m.NormalizedHash = new(string)
				*_m.NormalizedHash = value.String
			}
		case document.FieldDocType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field doc_type", values[i])
			} else if value.Valid {
				_m.DocType = value.String
			}
		case document.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = new(string)
				*_m.ContentType = value.String
			}
		case document.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = new(int64)
				*_m.Size = value.Int64
			}
		case document.FieldDuplicateOf:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field duplicate_of", values[i])
			} else if value.Valid {
				_m.DuplicateOf = new(xid.ID)
				*_m.DuplicateOf = *value.S.(*xid.ID)
			}
		case document.FieldHasPii:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_pii", values[i])
			} else if value.Valid {
				_m.HasPii = value.Bool
			}
		case document.FieldPiiSummary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field pii_summary", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PiiSummary); err != nil {
					return fmt.Errorf("unmarshal field pii_summary: %w", err)
				}
			}
		case document.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Document.
// This includes values selected through modifiers, order, etc.
func (_m *Document) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the Document entity.
func (_m *Document) QueryTenant() *TenantQuery {
	return NewDocumentClient(_m.config).QueryTenant(_m)
}

// QueryChunks queries the "chunks" edge of the Document entity.
func (_m *Document) QueryChunks() *ChunkQuery {
	return NewDocumentClient(_m.config).QueryChunks(_m)
}

// Update returns a builder for updating this Document.
// Note that you need to call Document.Unwrap() before calling this method if this Document
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Document) Update() *DocumentUpdateOne {
	return NewDocumentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Document entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Document) Unwrap() *Document {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Document is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Document) String() string {
	var builder strings.Builder
	builder.WriteString("Document(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("source_url=")
	builder.WriteString(_m.SourceURL)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.NormalizedHash; v != nil {
		builder.WriteString("normalized_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("doc_type=")
	builder.WriteString(_m.DocType)
	builder.WriteString(", ")
	if v := _m.ContentType; v != nil {
		builder.WriteString("content_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Size; v != nil {
		builder.WriteString("size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DuplicateOf; v != nil {
		builder.WriteString("duplicate_of=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("has_pii=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasPii))
	builder.WriteString(", ")
	builder.WriteString("pii_summary=")
	builder.WriteString(fmt.Sprintf("%v", _m.PiiSummary))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Documents is a parsable slice of Document.
type Documents []*Document
