// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/ingestjob"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/predicate"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/tenant"
	"github.com/rs/xid"
)

// IngestJobUpdate is the builder for updating IngestJob entities.
type IngestJobUpdate struct {
	config
	hooks    []Hook
	mutation *IngestJobMutation
}

// Where appends a list predicates to the IngestJobUpdate builder.
func (_u *IngestJobUpdate) Where(ps ...predicate.IngestJob) *IngestJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *IngestJobUpdate) SetTenantID(v xid.ID) *IngestJobUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *IngestJobUpdate) SetNillableTenantID(v *xid.ID) *IngestJobUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IngestJobUpdate) SetStatus(v ingestjob.Status) *IngestJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IngestJobUpdate) SetNillableStatus(v *ingestjob.Status) *IngestJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *IngestJobUpdate) SetSourceType(v string) *IngestJobUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *IngestJobUpdate) SetNillableSourceType(v *string) *IngestJobUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourcePayload sets the "source_payload" field.
func (_u *IngestJobUpdate) SetSourcePayload(v map[string]interface{}) *IngestJobUpdate {
	_u.mutation.SetSourcePayload(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *IngestJobUpdate) SetMessage(v string) *IngestJobUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *IngestJobUpdate) SetNillableMessage(v *string) *IngestJobUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *IngestJobUpdate) ClearMessage() *IngestJobUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetProgress sets the "progress" field.
func (_u *IngestJobUpdate) SetProgress(v int) *IngestJobUpdate {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *IngestJobUpdate) SetNillableProgress(v *int) *IngestJobUpdate {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *IngestJobUpdate) AddProgress(v int) *IngestJobUpdate {
	_u.mutation.AddProgress(v)
	return _u
}

// SetHasContentFindings sets the "has_content_findings" field.
func (_u *IngestJobUpdate) SetHasContentFindings(v bool) *IngestJobUpdate {
	_u.mutation.SetHasContentFindings(v)
	return _u
}

// SetNillableHasContentFindings sets the "has_content_findings" field if the given value is not nil.
func (_u *IngestJobUpdate) SetNillableHasContentFindings(v *bool) *IngestJobUpdate {
	if v != nil {
		_u.SetHasContentFindings(*v)
	}
	return _u
}

// SetContentFindings sets the "content_findings" field.
func (_u *IngestJobUpdate) SetContentFindings(v map[string]interface{}) *IngestJobUpdate {
	_u.mutation.SetContentFindings(v)
	return _u
}

// ClearContentFindings clears the value of the "content_findings" field.
func (_u *IngestJobUpdate) ClearContentFindings() *IngestJobUpdate {
	_u.mutation.ClearContentFindings()
	return _u
}

// SetContentDetectionProfile sets the "content_detection_profile" field.
func (_u *IngestJobUpdate) SetContentDetectionProfile(v string) *IngestJobUpdate {
	_u.mutation.SetContentDetectionProfile(v)
	return _u
}

// SetNillableContentDetectionProfile sets the "content_detection_profile" field if the given value is not nil.
func (_u *IngestJobUpdate) SetNillableContentDetectionProfile(v *string) *IngestJobUpdate {
	if v != nil {
		_u.SetContentDetectionProfile(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IngestJobUpdate) SetCreatedAt(v time.Time) *IngestJobUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IngestJobUpdate) SetNillableCreatedAt(v *time.Time) *IngestJobUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IngestJobUpdate) SetUpdatedAt(v time.Time) *IngestJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *IngestJobUpdate) SetTenant(v *Tenant) *IngestJobUpdate {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the IngestJobMutation object of the builder.
func (_u *IngestJobUpdate) Mutation() *IngestJobMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *IngestJobUpdate) ClearTenant() *IngestJobUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IngestJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IngestJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IngestJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IngestJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IngestJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ingestjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IngestJobUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := ingestjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IngestJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := ingestjob.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "IngestJob.source_type": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IngestJob.tenant"`)
	}
	return nil
}

func (_u *IngestJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ingestjob.Table, ingestjob.Columns, sqlgraph.NewFieldSpec(ingestjob.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ingestjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(ingestjob.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourcePayload(); ok {
		_spec.SetField(ingestjob.FieldSourcePayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(ingestjob.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(ingestjob.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(ingestjob.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(ingestjob.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HasContentFindings(); ok {
		_spec.SetField(ingestjob.FieldHasContentFindings, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ContentFindings(); ok {
		_spec.SetField(ingestjob.FieldContentFindings, field.TypeJSON, value)
	}
	if _u.mutation.ContentFindingsCleared() {
		_spec.ClearField(ingestjob.FieldContentFindings, field.TypeJSON)
	}
	if value, ok := _u.mutation.ContentDetectionProfile(); ok {
		_spec.SetField(ingestjob.FieldContentDetectionProfile, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(ingestjob.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ingestjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestjob.TenantTable,
			Columns: []string{ingestjob.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestjob.TenantTable,
			Columns: []string{ingestjob.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ingestjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IngestJobUpdateOne is the builder for updating a single IngestJob entity.
type IngestJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IngestJobMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *IngestJobUpdateOne) SetTenantID(v xid.ID) *IngestJobUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *IngestJobUpdateOne) SetNillableTenantID(v *xid.ID) *IngestJobUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IngestJobUpdateOne) SetStatus(v ingestjob.Status) *IngestJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IngestJobUpdateOne) SetNillableStatus(v *ingestjob.Status) *IngestJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *IngestJobUpdateOne) SetSourceType(v string) *IngestJobUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *IngestJobUpdateOne) SetNillableSourceType(v *string) *IngestJobUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourcePayload sets the "source_payload" field.
func (_u *IngestJobUpdateOne) SetSourcePayload(v map[string]interface{}) *IngestJobUpdateOne {
	_u.mutation.SetSourcePayload(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *IngestJobUpdateOne) SetMessage(v string) *IngestJobUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *IngestJobUpdateOne) SetNillableMessage(v *string) *IngestJobUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *IngestJobUpdateOne) ClearMessage() *IngestJobUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetProgress sets the "progress" field.
func (_u *IngestJobUpdateOne) SetProgress(v int) *IngestJobUpdateOne {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *IngestJobUpdateOne) SetNillableProgress(v *int) *IngestJobUpdateOne {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *IngestJobUpdateOne) AddProgress(v int) *IngestJobUpdateOne {
	_u.mutation.AddProgress(v)
	return _u
}

// SetHasContentFindings sets the "has_content_findings" field.
func (_u *IngestJobUpdateOne) SetHasContentFindings(v bool) *IngestJobUpdateOne {
	_u.mutation.SetHasContentFindings(v)
	return _u
}

// SetNillableHasContentFindings sets the "has_content_findings" field if the given value is not nil.
func (_u *IngestJobUpdateOne) SetNillableHasContentFindings(v *bool) *IngestJobUpdateOne {
	if v != nil {
		_u.SetHasContentFindings(*v)
	}
	return _u
}

// SetContentFindings sets the "content_findings" field.
func (_u *IngestJobUpdateOne) SetContentFindings(v map[string]interface{}) *IngestJobUpdateOne {
	_u.mutation.SetContentFindings(v)
	return _u
}

// ClearContentFindings clears the value of the "content_findings" field.
func (_u *IngestJobUpdateOne) ClearContentFindings() *IngestJobUpdateOne {
	_u.mutation.ClearContentFindings()
	return _u
}

// SetContentDetectionProfile sets the "content_detection_profile" field.
func (_u *IngestJobUpdateOne) SetContentDetectionProfile(v string) *IngestJobUpdateOne {
	_u.mutation.SetContentDetectionProfile(v)
	return _u
}

// SetNillableContentDetectionProfile sets the "content_detection_profile" field if the given value is not nil.
func (_u *IngestJobUpdateOne) SetNillableContentDetectionProfile(v *string) *IngestJobUpdateOne {
	if v != nil {
		_u.SetContentDetectionProfile(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IngestJobUpdateOne) SetCreatedAt(v time.Time) *IngestJobUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IngestJobUpdateOne) SetNillableCreatedAt(v *time.Time) *IngestJobUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IngestJobUpdateOne) SetUpdatedAt(v time.Time) *IngestJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *IngestJobUpdateOne) SetTenant(v *Tenant) *IngestJobUpdateOne {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the IngestJobMutation object of the builder.
func (_u *IngestJobUpdateOne) Mutation() *IngestJobMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *IngestJobUpdateOne) ClearTenant() *IngestJobUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// Where appends a list predicates to the IngestJobUpdate builder.
func (_u *IngestJobUpdateOne) Where(ps ...predicate.IngestJob) *IngestJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IngestJobUpdateOne) Select(field string, fields ...string) *IngestJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IngestJob entity.
func (_u *IngestJobUpdateOne) Save(ctx context.Context) (*IngestJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IngestJobUpdateOne) SaveX(ctx context.Context) *IngestJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IngestJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IngestJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IngestJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ingestjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IngestJobUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := ingestjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IngestJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := ingestjob.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "IngestJob.source_type": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IngestJob.tenant"`)
	}
	return nil
}

func (_u *IngestJobUpdateOne) sqlSave(ctx context.Context) (_node *IngestJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ingestjob.Table, ingestjob.Columns, sqlgraph.NewFieldSpec(ingestjob.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IngestJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ingestjob.FieldID)
		for _, f := range fields {
			if !ingestjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ingestjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ingestjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(ingestjob.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourcePayload(); ok {
		_spec.SetField(ingestjob.FieldSourcePayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(ingestjob.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(ingestjob.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(ingestjob.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(ingestjob.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HasContentFindings(); ok {
		_spec.SetField(ingestjob.FieldHasContentFindings, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ContentFindings(); ok {
		_spec.SetField(ingestjob.FieldContentFindings, field.TypeJSON, value)
	}
	if _u.mutation.ContentFindingsCleared() {
		_spec.ClearField(ingestjob.FieldContentFindings, field.TypeJSON)
	}
	if value, ok := _u.mutation.ContentDetectionProfile(); ok {
		_spec.SetField(ingestjob.FieldContentDetectionProfile, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(ingestjob.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ingestjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestjob.TenantTable,
			Columns: []string{ingestjob.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestjob.TenantTable,
			Columns: []string{ingestjob.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IngestJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ingestjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
