// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/ingestjob"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/tenant"
	"github.com/rs/xid"
)

// IngestJob is the model entity for the IngestJob schema.
type IngestJob struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID xid.ID `json:"tenant_id,omitempty"`
	// Status holds the value of the "status" field.
	Status ingestjob.Status `json:"status,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// SourcePayload holds the value of the "source_payload" field.
	SourcePayload map[string]interface{} `json:"source_payload,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// Progress holds the value of the "progress" field.
	Progress int `json:"progress,omitempty"`
	// HasContentFindings holds the value of the "has_content_findings" field.
	HasContentFindings bool `json:"has_content_findings,omitempty"`
	// ContentFindings holds the value of the "content_findings" field.
	ContentFindings map[string]interface{} `json:"content_findings,omitempty"`
	// ContentDetectionProfile holds the value of the "content_detection_profile" field.
	ContentDetectionProfile string `json:"content_detection_profile,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IngestJobQuery when eager-loading is set.
	Edges        IngestJobEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IngestJobEdges holds the relations/edges for other nodes in the graph.
type IngestJobEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IngestJobEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IngestJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ingestjob.FieldSourcePayload, ingestjob.FieldContentFindings:
			values[i] = new([]byte)
		case ingestjob.FieldHasContentFindings:
			values[i] = new(sql.NullBool)
		case ingestjob.FieldProgress:
			values[i] = new(sql.NullInt64)
		case ingestjob.FieldStatus, ingestjob.FieldSourceType, ingestjob.FieldMessage, ingestjob.FieldContentDetectionProfile:
			values[i] = new(sql.NullString)
		case ingestjob.FieldCreatedAt, ingestjob.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case ingestjob.FieldID, ingestjob.FieldTenantID:
			values[i] = new(xid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IngestJob fields.
func (_m *IngestJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ingestjob.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case ingestjob.FieldTenantID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case ingestjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = ingestjob.Status(value.String)
			}
		case ingestjob.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case ingestjob.FieldSourcePayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field source_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SourcePayload); err != nil {
					return fmt.Errorf("unmarshal field source_payload: %w", err)
				}
			}
		case ingestjob.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case ingestjob.FieldProgress:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field progress", values[i])
			} else if value.Valid {
				_m.Progress = int(value.Int64)
			}
		case ingestjob.FieldHasContentFindings:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_content_findings", values[i])
			} else if value.Valid {
				_m.HasContentFindings = value.Bool
			}
		case ingestjob.FieldContentFindings:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field content_findings", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ContentFindings); err != nil {
					return fmt.Errorf("unmarshal field content_findings: %w", err)
				}
			}
		case ingestjob.FieldContentDetectionProfile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_detection_profile", values[i])
			} else if value.Valid {
				_m.ContentDetectionProfile = value.String
			}
		case ingestjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ingestjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IngestJob.
// This includes values selected through modifiers, order, etc.
func (_m *IngestJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the IngestJob entity.
func (_m *IngestJob) QueryTenant() *TenantQuery {
	return NewIngestJobClient(_m.config).QueryTenant(_m)
}

// Update returns a builder for updating this IngestJob.
// Note that you need to call IngestJob.Unwrap() before calling this method if this IngestJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IngestJob) Update() *IngestJobUpdateOne {
	return NewIngestJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IngestJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IngestJob) Unwrap() *IngestJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IngestJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IngestJob) String() string {
	var builder strings.Builder
	builder.WriteString("IngestJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("source_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourcePayload))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("progress=")
	builder.WriteString(fmt.Sprintf("%v", _m.Progress))
	builder.WriteString(", ")
	builder.WriteString("has_content_findings=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasContentFindings))
	builder.WriteString(", ")
	builder.WriteString("content_findings=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContentFindings))
	builder.WriteString(", ")
	builder.WriteString("content_detection_profile=")
	builder.WriteString(_m.ContentDetectionProfile)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// IngestJobs is a parsable slice of IngestJob.
type IngestJobs []*IngestJob
