// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/ingestjob"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/tenant"
	"github.com/rs/xid"
)

// IngestJobCreate is the builder for creating a IngestJob entity.
type IngestJobCreate struct {
	config
	mutation *IngestJobMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *IngestJobCreate) SetTenantID(v xid.ID) *IngestJobCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *IngestJobCreate) SetStatus(v ingestjob.Status) *IngestJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IngestJobCreate) SetNillableStatus(v *ingestjob.Status) *IngestJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *IngestJobCreate) SetSourceType(v string) *IngestJobCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourcePayload sets the "source_payload" field.
func (_c *IngestJobCreate) SetSourcePayload(v map[string]interface{}) *IngestJobCreate {
	_c.mutation.SetSourcePayload(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *IngestJobCreate) SetMessage(v string) *IngestJobCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *IngestJobCreate) SetNillableMessage(v *string) *IngestJobCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetProgress sets the "progress" field.
func (_c *IngestJobCreate) SetProgress(v int) *IngestJobCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *IngestJobCreate) SetNillableProgress(v *int) *IngestJobCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetHasContentFindings sets the "has_content_findings" field.
func (_c *IngestJobCreate) SetHasContentFindings(v bool) *IngestJobCreate {
	_c.mutation.SetHasContentFindings(v)
	return _c
}

// SetNillableHasContentFindings sets the "has_content_findings" field if the given value is not nil.
func (_c *IngestJobCreate) SetNillableHasContentFindings(v *bool) *IngestJobCreate {
	if v != nil {
		_c.SetHasContentFindings(*v)
	}
	return _c
}

// SetContentFindings sets the "content_findings" field.
func (_c *IngestJobCreate) SetContentFindings(v map[string]interface{}) *IngestJobCreate {
	_c.mutation.SetContentFindings(v)
	return _c
}

// SetContentDetectionProfile sets the "content_detection_profile" field.
func (_c *IngestJobCreate) SetContentDetectionProfile(v string) *IngestJobCreate {
	_c.mutation.SetContentDetectionProfile(v)
	return _c
}

// SetNillableContentDetectionProfile sets the "content_detection_profile" field if the given value is not nil.
func (_c *IngestJobCreate) SetNillableContentDetectionProfile(v *string) *IngestJobCreate {
	if v != nil {
		_c.SetContentDetectionProfile(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IngestJobCreate) SetCreatedAt(v time.Time) *IngestJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IngestJobCreate) SetNillableCreatedAt(v *time.Time) *IngestJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IngestJobCreate) SetUpdatedAt(v time.Time) *IngestJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IngestJobCreate) SetNillableUpdatedAt(v *time.Time) *IngestJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IngestJobCreate) SetID(v xid.ID) *IngestJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *IngestJobCreate) SetNillableID(v *xid.ID) *IngestJobCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *IngestJobCreate) SetTenant(v *Tenant) *IngestJobCreate {
	return _c.SetTenantID(v.ID)
}

// Mutation returns the IngestJobMutation object of the builder.
func (_c *IngestJobCreate) Mutation() *IngestJobMutation {
	return _c.mutation
}

// Save creates the IngestJob in the database.
func (_c *IngestJobCreate) Save(ctx context.Context) (*IngestJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IngestJobCreate) SaveX(ctx context.Context) *IngestJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IngestJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IngestJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IngestJobCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := ingestjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Progress(); !ok {
		v := ingestjob.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.HasContentFindings(); !ok {
		v := ingestjob.DefaultHasContentFindings
		_c.mutation.SetHasContentFindings(v)
	}
	if _, ok := _c.mutation.ContentDetectionProfile(); !ok {
		v := ingestjob.DefaultContentDetectionProfile
		_c.mutation.SetContentDetectionProfile(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ingestjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ingestjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := ingestjob.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IngestJobCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "IngestJob.tenant_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IngestJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ingestjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IngestJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "IngestJob.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := ingestjob.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "IngestJob.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourcePayload(); !ok {
		return &ValidationError{Name: "source_payload", err: errors.New(`ent: missing required field "IngestJob.source_payload"`)}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "IngestJob.progress"`)}
	}
	if _, ok := _c.mutation.HasContentFindings(); !ok {
		return &ValidationError{Name: "has_content_findings", err: errors.New(`ent: missing required field "IngestJob.has_content_findings"`)}
	}
	if _, ok := _c.mutation.ContentDetectionProfile(); !ok {
		return &ValidationError{Name: "content_detection_profile", err: errors.New(`ent: missing required field "IngestJob.content_detection_profile"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IngestJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IngestJob.updated_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "IngestJob.tenant"`)}
	}
	return nil
}

func (_c *IngestJobCreate) sqlSave(ctx context.Context) (*IngestJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IngestJobCreate) createSpec() (*IngestJob, *sqlgraph.CreateSpec) {
	var (
		_node = &IngestJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ingestjob.Table, sqlgraph.NewFieldSpec(ingestjob.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ingestjob.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(ingestjob.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourcePayload(); ok {
		_spec.SetField(ingestjob.FieldSourcePayload, field.TypeJSON, value)
		_node.SourcePayload = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(ingestjob.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(ingestjob.FieldProgress, field.TypeInt, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.HasContentFindings(); ok {
		_spec.SetField(ingestjob.FieldHasContentFindings, field.TypeBool, value)
		_node.HasContentFindings = value
	}
	if value, ok := _c.mutation.ContentFindings(); ok {
		_spec.SetField(ingestjob.FieldContentFindings, field.TypeJSON, value)
		_node.ContentFindings = value
	}
	if value, ok := _c.mutation.ContentDetectionProfile(); ok {
		_spec.SetField(ingestjob.FieldContentDetectionProfile, field.TypeString, value)
		_node.ContentDetectionProfile = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ingestjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ingestjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ingestjob.TenantTable,
			Columns: []string{ingestjob.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IngestJobCreateBulk is the builder for creating many IngestJob entities in bulk.
type IngestJobCreateBulk struct {
	config
	err      error
	builders []*IngestJobCreate
}

// Save creates the IngestJob entities in the database.
func (_c *IngestJobCreateBulk) Save(ctx context.Context) ([]*IngestJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IngestJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IngestJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IngestJobCreateBulk) SaveX(ctx context.Context) []*IngestJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IngestJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IngestJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
