// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/interaction"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/predicate"
	"github.com/rs/xid"
)

// InteractionUpdate is the builder for updating Interaction entities.
type InteractionUpdate struct {
	config
	hooks    []Hook
	mutation *InteractionMutation
}

// Where appends a list predicates to the InteractionUpdate builder.
func (_u *InteractionUpdate) Where(ps ...predicate.Interaction) *InteractionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeploymentID sets the "deployment_id" field.
func (_u *InteractionUpdate) SetDeploymentID(v xid.ID) *InteractionUpdate {
	_u.mutation.SetDeploymentID(v)
	return _u
}

// SetNillableDeploymentID sets the "deployment_id" field if the given value is not nil.
func (_u *InteractionUpdate) SetNillableDeploymentID(v *xid.ID) *InteractionUpdate {
	if v != nil {
		_u.SetDeploymentID(*v)
	}
	return _u
}

// ClearDeploymentID clears the value of the "deployment_id" field.
func (_u *InteractionUpdate) ClearDeploymentID() *InteractionUpdate {
	_u.mutation.ClearDeploymentID()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *InteractionUpdate) SetTenantID(v xid.ID) *InteractionUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *InteractionUpdate) SetNillableTenantID(v *xid.ID) *InteractionUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *InteractionUpdate) SetEventType(v string) *InteractionUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *InteractionUpdate) SetNillableEventType(v *string) *InteractionUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetQuery sets the "query" field.
func (_u *InteractionUpdate) SetQuery(v string) *InteractionUpdate {
	_u.mutation.SetQuery(v)
	return _u
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_u *InteractionUpdate) SetNillableQuery(v *string) *InteractionUpdate {
	if v != nil {
		_u.SetQuery(*v)
	}
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *InteractionUpdate) SetAnswer(v string) *InteractionUpdate {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *InteractionUpdate) SetNillableAnswer(v *string) *InteractionUpdate {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// ClearAnswer clears the value of the "answer" field.
func (_u *InteractionUpdate) ClearAnswer() *InteractionUpdate {
	_u.mutation.ClearAnswer()
	return _u
}

// SetHelpful sets the "helpful" field.
func (_u *InteractionUpdate) SetHelpful(v bool) *InteractionUpdate {
	_u.mutation.SetHelpful(v)
	return _u
}

// SetNillableHelpful sets the "helpful" field if the given value is not nil.
func (_u *InteractionUpdate) SetNillableHelpful(v *bool) *InteractionUpdate {
	if v != nil {
		_u.SetHelpful(*v)
	}
	return _u
}

// ClearHelpful clears the value of the "helpful" field.
func (_u *InteractionUpdate) ClearHelpful() *InteractionUpdate {
	_u.mutation.ClearHelpful()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *InteractionUpdate) SetDurationMs(v int) *InteractionUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *InteractionUpdate) SetNillableDurationMs(v *int) *InteractionUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *InteractionUpdate) AddDurationMs(v int) *InteractionUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *InteractionUpdate) ClearDurationMs() *InteractionUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InteractionUpdate) SetCreatedAt(v time.Time) *InteractionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InteractionUpdate) SetNillableCreatedAt(v *time.Time) *InteractionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the InteractionMutation object of the builder.
func (_u *InteractionUpdate) Mutation() *InteractionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InteractionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InteractionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InteractionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InteractionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InteractionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(interaction.Table, interaction.Columns, sqlgraph.NewFieldSpec(interaction.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeploymentID(); ok {
		_spec.SetField(interaction.FieldDeploymentID, field.TypeString, value)
	}
	if _u.mutation.DeploymentIDCleared() {
		_spec.ClearField(interaction.FieldDeploymentID, field.TypeString)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(interaction.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(interaction.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(interaction.FieldQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(interaction.FieldAnswer, field.TypeString, value)
	}
	if _u.mutation.AnswerCleared() {
		_spec.ClearField(interaction.FieldAnswer, field.TypeString)
	}
	if value, ok := _u.mutation.Helpful(); ok {
		_spec.SetField(interaction.FieldHelpful, field.TypeBool, value)
	}
	if _u.mutation.HelpfulCleared() {
		_spec.ClearField(interaction.FieldHelpful, field.TypeBool)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(interaction.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(interaction.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(interaction.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(interaction.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InteractionUpdateOne is the builder for updating a single Interaction entity.
type InteractionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InteractionMutation
}

// SetDeploymentID sets the "deployment_id" field.
func (_u *InteractionUpdateOne) SetDeploymentID(v xid.ID) *InteractionUpdateOne {
	_u.mutation.SetDeploymentID(v)
	return _u
}

// SetNillableDeploymentID sets the "deployment_id" field if the given value is not nil.
func (_u *InteractionUpdateOne) SetNillableDeploymentID(v *xid.ID) *InteractionUpdateOne {
	if v != nil {
		_u.SetDeploymentID(*v)
	}
	return _u
}

// ClearDeploymentID clears the value of the "deployment_id" field.
func (_u *InteractionUpdateOne) ClearDeploymentID() *InteractionUpdateOne {
	_u.mutation.ClearDeploymentID()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *InteractionUpdateOne) SetTenantID(v xid.ID) *InteractionUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *InteractionUpdateOne) SetNillableTenantID(v *xid.ID) *InteractionUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *InteractionUpdateOne) SetEventType(v string) *InteractionUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *InteractionUpdateOne) SetNillableEventType(v *string) *InteractionUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetQuery sets the "query" field.
func (_u *InteractionUpdateOne) SetQuery(v string) *InteractionUpdateOne {
	_u.mutation.SetQuery(v)
	return _u
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_u *InteractionUpdateOne) SetNillableQuery(v *string) *InteractionUpdateOne {
	if v != nil {
		_u.SetQuery(*v)
	}
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *InteractionUpdateOne) SetAnswer(v string) *InteractionUpdateOne {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *InteractionUpdateOne) SetNillableAnswer(v *string) *InteractionUpdateOne {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// ClearAnswer clears the value of the "answer" field.
func (_u *InteractionUpdateOne) ClearAnswer() *InteractionUpdateOne {
	_u.mutation.ClearAnswer()
	return _u
}

// SetHelpful sets the "helpful" field.
func (_u *InteractionUpdateOne) SetHelpful(v bool) *InteractionUpdateOne {
	_u.mutation.SetHelpful(v)
	return _u
}

// SetNillableHelpful sets the "helpful" field if the given value is not nil.
func (_u *InteractionUpdateOne) SetNillableHelpful(v *bool) *InteractionUpdateOne {
	if v != nil {
		_u.SetHelpful(*v)
	}
	return _u
}

// ClearHelpful clears the value of the "helpful" field.
func (_u *InteractionUpdateOne) ClearHelpful() *InteractionUpdateOne {
	_u.mutation.ClearHelpful()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *InteractionUpdateOne) SetDurationMs(v int) *InteractionUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *InteractionUpdateOne) SetNillableDurationMs(v *int) *InteractionUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *InteractionUpdateOne) AddDurationMs(v int) *InteractionUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *InteractionUpdateOne) ClearDurationMs() *InteractionUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InteractionUpdateOne) SetCreatedAt(v time.Time) *InteractionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InteractionUpdateOne) SetNillableCreatedAt(v *time.Time) *InteractionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the InteractionMutation object of the builder.
func (_u *InteractionUpdateOne) Mutation() *InteractionMutation {
	return _u.mutation
}

// Where appends a list predicates to the InteractionUpdate builder.
func (_u *InteractionUpdateOne) Where(ps ...predicate.Interaction) *InteractionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InteractionUpdateOne) Select(field string, fields ...string) *InteractionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Interaction entity.
func (_u *InteractionUpdateOne) Save(ctx context.Context) (*Interaction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InteractionUpdateOne) SaveX(ctx context.Context) *Interaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InteractionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InteractionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InteractionUpdateOne) sqlSave(ctx context.Context) (_node *Interaction, err error) {
	_spec := sqlgraph.NewUpdateSpec(interaction.Table, interaction.Columns, sqlgraph.NewFieldSpec(interaction.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Interaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, interaction.FieldID)
		for _, f := range fields {
			if !interaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != interaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeploymentID(); ok {
		_spec.SetField(interaction.FieldDeploymentID, field.TypeString, value)
	}
	if _u.mutation.DeploymentIDCleared() {
		_spec.ClearField(interaction.FieldDeploymentID, field.TypeString)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(interaction.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(interaction.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(interaction.FieldQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(interaction.FieldAnswer, field.TypeString, value)
	}
	if _u.mutation.AnswerCleared() {
		_spec.ClearField(interaction.FieldAnswer, field.TypeString)
	}
	if value, ok := _u.mutation.Helpful(); ok {
		_spec.SetField(interaction.FieldHelpful, field.TypeBool, value)
	}
	if _u.mutation.HelpfulCleared() {
		_spec.ClearField(interaction.FieldHelpful, field.TypeBool)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(interaction.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(interaction.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(interaction.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(interaction.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Interaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
