// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/interaction"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/predicate"
)

// InteractionDelete is the builder for deleting a Interaction entity.
type InteractionDelete struct {
	config
	hooks    []Hook
	mutation *InteractionMutation
}

// Where appends a list predicates to the InteractionDelete builder.
func (_d *InteractionDelete) Where(ps ...predicate.Interaction) *InteractionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InteractionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InteractionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InteractionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(interaction.Table, sqlgraph.NewFieldSpec(interaction.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InteractionDeleteOne is the builder for deleting a single Interaction entity.
type InteractionDeleteOne struct {
	_d *InteractionDelete
}

// Where appends a list predicates to the InteractionDelete builder.
func (_d *InteractionDeleteOne) Where(ps ...predicate.Interaction) *InteractionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InteractionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{interaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InteractionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
