// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/interaction"
	"github.com/rs/xid"
)

// InteractionCreate is the builder for creating a Interaction entity.
type InteractionCreate struct {
	config
	mutation *InteractionMutation
	hooks    []Hook
}

// SetDeploymentID sets the "deployment_id" field.
func (_c *InteractionCreate) SetDeploymentID(v xid.ID) *InteractionCreate {
	_c.mutation.SetDeploymentID(v)
	return _c
}

// SetNillableDeploymentID sets the "deployment_id" field if the given value is not nil.
func (_c *InteractionCreate) SetNillableDeploymentID(v *xid.ID) *InteractionCreate {
	if v != nil {
		_c.SetDeploymentID(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *InteractionCreate) SetTenantID(v xid.ID) *InteractionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *InteractionCreate) SetEventType(v string) *InteractionCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetQuery sets the "query" field.
func (_c *InteractionCreate) SetQuery(v string) *InteractionCreate {
	_c.mutation.SetQuery(v)
	return _c
}

// SetAnswer sets the "answer" field.
func (_c *InteractionCreate) SetAnswer(v string) *InteractionCreate {
	_c.mutation.SetAnswer(v)
	return _c
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_c *InteractionCreate) SetNillableAnswer(v *string) *InteractionCreate {
	if v != nil {
		_c.SetAnswer(*v)
	}
	return _c
}

// SetHelpful sets the "helpful" field.
func (_c *InteractionCreate) SetHelpful(v bool) *InteractionCreate {
	_c.mutation.SetHelpful(v)
	return _c
}

// SetNillableHelpful sets the "helpful" field if the given value is not nil.
func (_c *InteractionCreate) SetNillableHelpful(v *bool) *InteractionCreate {
	if v != nil {
		_c.SetHelpful(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *InteractionCreate) SetDurationMs(v int) *InteractionCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *InteractionCreate) SetNillableDurationMs(v *int) *InteractionCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InteractionCreate) SetCreatedAt(v time.Time) *InteractionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InteractionCreate) SetNillableCreatedAt(v *time.Time) *InteractionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InteractionCreate) SetID(v xid.ID) *InteractionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InteractionCreate) SetNillableID(v *xid.ID) *InteractionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the InteractionMutation object of the builder.
func (_c *InteractionCreate) Mutation() *InteractionMutation {
	return _c.mutation
}

// Save creates the Interaction in the database.
func (_c *InteractionCreate) Save(ctx context.Context) (*Interaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InteractionCreate) SaveX(ctx context.Context) *Interaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InteractionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InteractionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InteractionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := interaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := interaction.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InteractionCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Interaction.tenant_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "Interaction.event_type"`)}
	}
	if _, ok := _c.mutation.Query(); !ok {
		return &ValidationError{Name: "query", err: errors.New(`ent: missing required field "Interaction.query"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Interaction.created_at"`)}
	}
	return nil
}

func (_c *InteractionCreate) sqlSave(ctx context.Context) (*Interaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InteractionCreate) createSpec() (*Interaction, *sqlgraph.CreateSpec) {
	var (
		_node = &Interaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(interaction.Table, sqlgraph.NewFieldSpec(interaction.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DeploymentID(); ok {
		_spec.SetField(interaction.FieldDeploymentID, field.TypeString, value)
		_node.DeploymentID = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(interaction.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(interaction.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Query(); ok {
		_spec.SetField(interaction.FieldQuery, field.TypeString, value)
		_node.Query = value
	}
	if value, ok := _c.mutation.Answer(); ok {
		_spec.SetField(interaction.FieldAnswer, field.TypeString, value)
		_node.Answer = value
	}
	if value, ok := _c.mutation.Helpful(); ok {
		_spec.SetField(interaction.FieldHelpful, field.TypeBool, value)
		_node.Helpful = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(interaction.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(interaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// InteractionCreateBulk is the builder for creating many Interaction entities in bulk.
type InteractionCreateBulk struct {
	config
	err      error
	builders []*InteractionCreate
}

// Save creates the Interaction entities in the database.
func (_c *InteractionCreateBulk) Save(ctx context.Context) ([]*Interaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Interaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InteractionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InteractionCreateBulk) SaveX(ctx context.Context) []*Interaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InteractionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InteractionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
