// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/interaction"
	"github.com/rs/xid"
)

// Interaction is the model entity for the Interaction schema.
type Interaction struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// DeploymentID holds the value of the "deployment_id" field.
	DeploymentID *xid.ID `json:"deployment_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID xid.ID `json:"tenant_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Query holds the value of the "query" field.
	Query string `json:"query,omitempty"`
	// Answer holds the value of the "answer" field.
	Answer string `json:"answer,omitempty"`
	// Helpful holds the value of the "helpful" field.
	Helpful bool `json:"helpful,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int `json:"duration_ms,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Interaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case interaction.FieldDeploymentID:
			values[i] = &sql.NullScanner{S: new(xid.ID)}
		case interaction.FieldHelpful:
			values[i] = new(sql.NullBool)
		case interaction.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case interaction.FieldEventType, interaction.FieldQuery, interaction.FieldAnswer:
			values[i] = new(sql.NullString)
		case interaction.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case interaction.FieldID, interaction.FieldTenantID:
			values[i] = new(xid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Interaction fields.
func (_m *Interaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case interaction.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case interaction.FieldDeploymentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field deployment_id", values[i])
			} else if value.Valid {
				_m.DeploymentID = new(xid.ID)
				*_m.DeploymentID = *value.S.(*xid.ID)
			}
		case interaction.FieldTenantID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case interaction.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case interaction.FieldQuery:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field query", values[i])
			} else if value.Valid {
				_m.Query = value.String
			}
		case interaction.FieldAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field answer", values[i])
			} else if value.Valid {
				_m.Answer = value.String
			}
		case interaction.FieldHelpful:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field helpful", values[i])
			} else if value.Valid {
				_m.Helpful = value.Bool
			}
		case interaction.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = int(value.Int64)
			}
		case interaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Interaction.
// This includes values selected through modifiers, order, etc.
func (_m *Interaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Interaction.
// Note that you need to call Interaction.Unwrap() before calling this method if this Interaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Interaction) Update() *InteractionUpdateOne {
	return NewInteractionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Interaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Interaction) Unwrap() *Interaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Interaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Interaction) String() string {
	var builder strings.Builder
	builder.WriteString("Interaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeploymentID; v != nil {
		builder.WriteString("deployment_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("query=")
	builder.WriteString(_m.Query)
	builder.WriteString(", ")
	builder.WriteString("answer=")
	builder.WriteString(_m.Answer)
	builder.WriteString(", ")
	builder.WriteString("helpful=")
	builder.WriteString(fmt.Sprintf("%v", _m.Helpful))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Interactions is a parsable slice of Interaction.
type Interactions []*Interaction
