// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/chunk"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/deployment"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/document"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/ingestjob"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/interaction"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/schema"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/tenant"
	"github.com/rs/xid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chunkFields := schema.Chunk{}.Fields()
	_ = chunkFields
	// chunkDescText is the schema descriptor for text field.
	chunkDescText := chunkFields[2].Descriptor()
	// chunk.TextValidator is a validator for the "text" field. It is called by the builders before save.
	chunk.TextValidator = chunkDescText.Validators[0].(func(string) error)
	// chunkDescID is the schema descriptor for id field.
	chunkDescID := chunkFields[0].Descriptor()
	// chunk.DefaultID holds the default value on creation for the id field.
	chunk.DefaultID = chunkDescID.Default.(func() xid.ID)
	deploymentFields := schema.Deployment{}.Fields()
	_ = deploymentFields
	// deploymentDescCreatedAt is the schema descriptor for created_at field.
	deploymentDescCreatedAt := deploymentFields[2].Descriptor()
	// deployment.DefaultCreatedAt holds the default value on creation for the created_at field.
	deployment.DefaultCreatedAt = deploymentDescCreatedAt.Default.(func() time.Time)
	// deploymentDescUpdatedAt is the schema descriptor for updated_at field.
	deploymentDescUpdatedAt := deploymentFields[3].Descriptor()
	// deployment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	deployment.DefaultUpdatedAt = deploymentDescUpdatedAt.Default.(func() time.Time)
	// deployment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	deployment.UpdateDefaultUpdatedAt = deploymentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deploymentDescID is the schema descriptor for id field.
	deploymentDescID := deploymentFields[0].Descriptor()
	// deployment.DefaultID holds the default value on creation for the id field.
	deployment.DefaultID = deploymentDescID.Default.(func() xid.ID)
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	// documentDescDocType is the schema descriptor for doc_type field.
	documentDescDocType := documentFields[6].Descriptor()
	// document.DefaultDocType holds the default value on creation for the doc_type field.
	document.DefaultDocType = documentDescDocType.Default.(string)
	// documentDescHasPii is the schema descriptor for has_pii field.
	documentDescHasPii := documentFields[10].Descriptor()
	// document.DefaultHasPii holds the default value on creation for the has_pii field.
	document.DefaultHasPii = documentDescHasPii.Default.(bool)
	// documentDescCreatedAt is the schema descriptor for created_at field.
	documentDescCreatedAt := documentFields[12].Descriptor()
	// document.DefaultCreatedAt holds the default value on creation for the created_at field.
	document.DefaultCreatedAt = documentDescCreatedAt.Default.(func() time.Time)
	// documentDescID is the schema descriptor for id field.
	documentDescID := documentFields[0].Descriptor()
	// document.DefaultID holds the default value on creation for the id field.
	document.DefaultID = documentDescID.Default.(func() xid.ID)
	ingestjobFields := schema.IngestJob{}.Fields()
	_ = ingestjobFields
	// ingestjobDescSourceType is the schema descriptor for source_type field.
	ingestjobDescSourceType := ingestjobFields[3].Descriptor()
	// ingestjob.SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	ingestjob.SourceTypeValidator = ingestjobDescSourceType.Validators[0].(func(string) error)
	// ingestjobDescProgress is the schema descriptor for progress field.
	ingestjobDescProgress := ingestjobFields[6].Descriptor()
	// ingestjob.DefaultProgress holds the default value on creation for the progress field.
	ingestjob.DefaultProgress = ingestjobDescProgress.Default.(int)
	// ingestjobDescHasContentFindings is the schema descriptor for has_content_findings field.
	ingestjobDescHasContentFindings := ingestjobFields[7].Descriptor()
	// ingestjob.DefaultHasContentFindings holds the default value on creation for the has_content_findings field.
	ingestjob.DefaultHasContentFindings = ingestjobDescHasContentFindings.Default.(bool)
	// ingestjobDescContentDetectionProfile is the schema descriptor for content_detection_profile field.
	ingestjobDescContentDetectionProfile := ingestjobFields[9].Descriptor()
	// ingestjob.DefaultContentDetectionProfile holds the default value on creation for the content_detection_profile field.
	ingestjob.DefaultContentDetectionProfile = ingestjobDescContentDetectionProfile.Default.(string)
	// ingestjobDescCreatedAt is the schema descriptor for created_at field.
	ingestjobDescCreatedAt := ingestjobFields[10].Descriptor()
	// ingestjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	ingestjob.DefaultCreatedAt = ingestjobDescCreatedAt.Default.(func() time.Time)
	// ingestjobDescUpdatedAt is the schema descriptor for updated_at field.
	ingestjobDescUpdatedAt := ingestjobFields[11].Descriptor()
	// ingestjob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ingestjob.DefaultUpdatedAt = ingestjobDescUpdatedAt.Default.(func() time.Time)
	// ingestjob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ingestjob.UpdateDefaultUpdatedAt = ingestjobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ingestjobDescID is the schema descriptor for id field.
	ingestjobDescID := ingestjobFields[0].Descriptor()
	// ingestjob.DefaultID holds the default value on creation for the id field.
	ingestjob.DefaultID = ingestjobDescID.Default.(func() xid.ID)
	interactionFields := schema.Interaction{}.Fields()
	_ = interactionFields
	// interactionDescCreatedAt is the schema descriptor for created_at field.
	interactionDescCreatedAt := interactionFields[8].Descriptor()
	// interaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	interaction.DefaultCreatedAt = interactionDescCreatedAt.Default.(func() time.Time)
	// interactionDescID is the schema descriptor for id field.
	interactionDescID := interactionFields[0].Descriptor()
	// interaction.DefaultID holds the default value on creation for the id field.
	interaction.DefaultID = interactionDescID.Default.(func() xid.ID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[2].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescIsDefault is the schema descriptor for is_default field.
	tenantDescIsDefault := tenantFields[4].Descriptor()
	// tenant.DefaultIsDefault holds the default value on creation for the is_default field.
	tenant.DefaultIsDefault = tenantDescIsDefault.Default.(bool)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[5].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[6].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() xid.ID)
}
