// Code generated by ent, DO NOT EDIT.

package ingestjob

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rs/xid"
)

const (
	// Label holds the string label denoting the ingestjob type in the database.
	Label = "ingest_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourcePayload holds the string denoting the source_payload field in the database.
	FieldSourcePayload = "source_payload"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldHasContentFindings holds the string denoting the has_content_findings field in the database.
	FieldHasContentFindings = "has_content_findings"
	// FieldContentFindings holds the string denoting the content_findings field in the database.
	FieldContentFindings = "content_findings"
	// FieldContentDetectionProfile holds the string denoting the content_detection_profile field in the database.
	FieldContentDetectionProfile = "content_detection_profile"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// Table holds the table name of the ingestjob in the database.
	Table = "ingest_jobs"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "ingest_jobs"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
)

// Columns holds all SQL columns for ingestjob fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldStatus,
	FieldSourceType,
	FieldSourcePayload,
	FieldMessage,
	FieldProgress,
	FieldHasContentFindings,
	FieldContentFindings,
	FieldContentDetectionProfile,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	SourceTypeValidator func(string) error
	// DefaultProgress holds the default value on creation for the "progress" field.
	DefaultProgress int
	// DefaultHasContentFindings holds the default value on creation for the "has_content_findings" field.
	DefaultHasContentFindings bool
	// DefaultContentDetectionProfile holds the default value on creation for the "content_detection_profile" field.
	DefaultContentDetectionProfile string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() xid.ID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusRunning   Status = "running"
	StatusFailed    Status = "failed"
	StatusCompleted Status = "completed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusRunning, StatusFailed, StatusCompleted:
		return nil
	default:
		return fmt.Errorf("ingestjob: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the IngestJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByHasContentFindings orders the results by the has_content_findings field.
func ByHasContentFindings(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHasContentFindings, opts...).ToFunc()
}

// ByContentDetectionProfile orders the results by the content_detection_profile field.
func ByContentDetectionProfile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentDetectionProfile, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
