// Code generated by ent, DO NOT EDIT.

package ingestjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/predicate"
	"github.com/rs/xid"
)

// ID filters vertices based on their ID field.
func ID(id xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldTenantID, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldSourceType, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldMessage, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v int) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldProgress, v))
}

// HasContentFindings applies equality check predicate on the "has_content_findings" field. It's identical to HasContentFindingsEQ.
func HasContentFindings(v bool) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldHasContentFindings, v))
}

// ContentDetectionProfile applies equality check predicate on the "content_detection_profile" field. It's identical to ContentDetectionProfileEQ.
func ContentDetectionProfile(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldContentDetectionProfile, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v xid.ID) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v xid.ID) predicate.IngestJob {
	vc := v.String()
	return predicate.IngestJob(sql.FieldContains(FieldTenantID, vc))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v xid.ID) predicate.IngestJob {
	vc := v.String()
	return predicate.IngestJob(sql.FieldHasPrefix(FieldTenantID, vc))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v xid.ID) predicate.IngestJob {
	vc := v.String()
	return predicate.IngestJob(sql.FieldHasSuffix(FieldTenantID, vc))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v xid.ID) predicate.IngestJob {
	vc := v.String()
	return predicate.IngestJob(sql.FieldEqualFold(FieldTenantID, vc))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v xid.ID) predicate.IngestJob {
	vc := v.String()
	return predicate.IngestJob(sql.FieldContainsFold(FieldTenantID, vc))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNotIn(FieldStatus, vs...))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldContainsFold(FieldSourceType, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.IngestJob {
	return predicate.IngestJob(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldContainsFold(FieldMessage, v))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v int) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v int) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...int) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...int) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v int) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v int) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v int) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v int) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLTE(FieldProgress, v))
}

// HasContentFindingsEQ applies the EQ predicate on the "has_content_findings" field.
func HasContentFindingsEQ(v bool) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldHasContentFindings, v))
}

// HasContentFindingsNEQ applies the NEQ predicate on the "has_content_findings" field.
func HasContentFindingsNEQ(v bool) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNEQ(FieldHasContentFindings, v))
}

// ContentFindingsIsNil applies the IsNil predicate on the "content_findings" field.
func ContentFindingsIsNil() predicate.IngestJob {
	return predicate.IngestJob(sql.FieldIsNull(FieldContentFindings))
}

// ContentFindingsNotNil applies the NotNil predicate on the "content_findings" field.
func ContentFindingsNotNil() predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNotNull(FieldContentFindings))
}

// ContentDetectionProfileEQ applies the EQ predicate on the "content_detection_profile" field.
func ContentDetectionProfileEQ(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldContentDetectionProfile, v))
}

// ContentDetectionProfileNEQ applies the NEQ predicate on the "content_detection_profile" field.
func ContentDetectionProfileNEQ(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNEQ(FieldContentDetectionProfile, v))
}

// ContentDetectionProfileIn applies the In predicate on the "content_detection_profile" field.
func ContentDetectionProfileIn(vs ...string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldIn(FieldContentDetectionProfile, vs...))
}

// ContentDetectionProfileNotIn applies the NotIn predicate on the "content_detection_profile" field.
func ContentDetectionProfileNotIn(vs ...string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNotIn(FieldContentDetectionProfile, vs...))
}

// ContentDetectionProfileGT applies the GT predicate on the "content_detection_profile" field.
func ContentDetectionProfileGT(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGT(FieldContentDetectionProfile, v))
}

// ContentDetectionProfileGTE applies the GTE predicate on the "content_detection_profile" field.
func ContentDetectionProfileGTE(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGTE(FieldContentDetectionProfile, v))
}

// ContentDetectionProfileLT applies the LT predicate on the "content_detection_profile" field.
func ContentDetectionProfileLT(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLT(FieldContentDetectionProfile, v))
}

// ContentDetectionProfileLTE applies the LTE predicate on the "content_detection_profile" field.
func ContentDetectionProfileLTE(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLTE(FieldContentDetectionProfile, v))
}

// ContentDetectionProfileContains applies the Contains predicate on the "content_detection_profile" field.
func ContentDetectionProfileContains(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldContains(FieldContentDetectionProfile, v))
}

// ContentDetectionProfileHasPrefix applies the HasPrefix predicate on the "content_detection_profile" field.
func ContentDetectionProfileHasPrefix(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldHasPrefix(FieldContentDetectionProfile, v))
}

// ContentDetectionProfileHasSuffix applies the HasSuffix predicate on the "content_detection_profile" field.
func ContentDetectionProfileHasSuffix(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldHasSuffix(FieldContentDetectionProfile, v))
}

// ContentDetectionProfileEqualFold applies the EqualFold predicate on the "content_detection_profile" field.
func ContentDetectionProfileEqualFold(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEqualFold(FieldContentDetectionProfile, v))
}

// ContentDetectionProfileContainsFold applies the ContainsFold predicate on the "content_detection_profile" field.
func ContentDetectionProfileContainsFold(v string) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldContainsFold(FieldContentDetectionProfile, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IngestJob {
	return predicate.IngestJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.IngestJob {
	return predicate.IngestJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.IngestJob {
	return predicate.IngestJob(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IngestJob) predicate.IngestJob {
	return predicate.IngestJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IngestJob) predicate.IngestJob {
	return predicate.IngestJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IngestJob) predicate.IngestJob {
	return predicate.IngestJob(sql.NotPredicates(p))
}
