// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChunksColumns holds the columns for the "chunks" table.
	ChunksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "text", Type: field.TypeString, Size: 2147483647},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "embedding_model", Type: field.TypeString, Nullable: true},
		{Name: "vector_id", Type: field.TypeString, Nullable: true},
		{Name: "embedding_int8", Type: field.TypeBytes, Nullable: true},
		{Name: "embedding_binary", Type: field.TypeBytes, Nullable: true},
		{Name: "document_id", Type: field.TypeString},
	}
	// ChunksTable holds the schema information for the "chunks" table.
	ChunksTable = &schema.Table{
		Name:       "chunks",
		Columns:    ChunksColumns,
		PrimaryKey: []*schema.Column{ChunksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "chunks_documents_chunks",
				Columns:    []*schema.Column{ChunksColumns[7]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DeploymentsColumns holds the columns for the "deployments" table.
	DeploymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DeploymentsTable holds the schema information for the "deployments" table.
	DeploymentsTable = &schema.Table{
		Name:       "deployments",
		Columns:    DeploymentsColumns,
		PrimaryKey: []*schema.Column{DeploymentsColumns[0]},
	}
	// DocumentsColumns holds the columns for the "documents" table.
	DocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "source_url", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "normalized_hash", Type: field.TypeString, Nullable: true},
		{Name: "doc_type", Type: field.TypeString, Default: "generic"},
		{Name: "content_type", Type: field.TypeString, Nullable: true},
		{Name: "size", Type: field.TypeInt64, Nullable: true},
		{Name: "duplicate_of", Type: field.TypeString, Nullable: true},
		{Name: "has_pii", Type: field.TypeBool, Default: false},
		{Name: "pii_summary", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeString},
	}
	// DocumentsTable holds the schema information for the "documents" table.
	DocumentsTable = &schema.Table{
		Name:       "documents",
		Columns:    DocumentsColumns,
		PrimaryKey: []*schema.Column{DocumentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "documents_tenants_documents",
				Columns:    []*schema.Column{DocumentsColumns[12]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// IngestJobsColumns holds the columns for the "ingest_jobs" table.
	IngestJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "failed", "completed"}, Default: "pending"},
		{Name: "source_type", Type: field.TypeString},
		{Name: "source_payload", Type: field.TypeJSON},
		{Name: "message", Type: field.TypeString, Nullable: true},
		{Name: "progress", Type: field.TypeInt, Default: 0},
		{Name: "has_content_findings", Type: field.TypeBool, Default: false},
		{Name: "content_findings", Type: field.TypeJSON, Nullable: true},
		{Name: "content_detection_profile", Type: field.TypeString, Default: "none"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeString},
	}
	// IngestJobsTable holds the schema information for the "ingest_jobs" table.
	IngestJobsTable = &schema.Table{
		Name:       "ingest_jobs",
		Columns:    IngestJobsColumns,
		PrimaryKey: []*schema.Column{IngestJobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ingest_jobs_tenants_ingest_jobs",
				Columns:    []*schema.Column{IngestJobsColumns[11]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// InteractionsColumns holds the columns for the "interactions" table.
	InteractionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "deployment_id", Type: field.TypeString, Nullable: true},
		{Name: "tenant_id", Type: field.TypeString},
		{Name: "event_type", Type: field.TypeString},
		{Name: "query", Type: field.TypeString, Size: 2147483647},
		{Name: "answer", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "helpful", Type: field.TypeBool, Nullable: true},
		{Name: "duration_ms", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// InteractionsTable holds the schema information for the "interactions" table.
	InteractionsTable = &schema.Table{
		Name:       "interactions",
		Columns:    InteractionsColumns,
		PrimaryKey: []*schema.Column{InteractionsColumns[0]},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "deployment_id", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "api_key_hash", Type: field.TypeString},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deployment_tenants", Type: field.TypeString, Nullable: true},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tenants_deployments_tenants",
				Columns:    []*schema.Column{TenantsColumns[7]},
				RefColumns: []*schema.Column{DeploymentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tenant_deployment_id_name",
				Unique:  true,
				Columns: []*schema.Column{TenantsColumns[1], TenantsColumns[2]},
			},
			{
				Name:    "tenant_deployment_id_is_default",
				Unique:  false,
				Columns: []*schema.Column{TenantsColumns[1], TenantsColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChunksTable,
		DeploymentsTable,
		DocumentsTable,
		IngestJobsTable,
		InteractionsTable,
		TenantsTable,
	}
)

func init() {
	ChunksTable.ForeignKeys[0].RefTable = DocumentsTable
	DocumentsTable.ForeignKeys[0].RefTable = TenantsTable
	IngestJobsTable.ForeignKeys[0].RefTable = TenantsTable
	TenantsTable.ForeignKeys[0].RefTable = DeploymentsTable
}
