// Code generated by ent, DO NOT EDIT.

package tenant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/agentmaurice/mcpchatui/mcp/rag/internal/storage/db/ent/predicate"
	"github.com/rs/xid"
)

// ID filters vertices based on their ID field.
func ID(id xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldID, id))
}

// DeploymentID applies equality check predicate on the "deployment_id" field. It's identical to DeploymentIDEQ.
func DeploymentID(v xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldDeploymentID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldName, v))
}

// APIKeyHash applies equality check predicate on the "api_key_hash" field. It's identical to APIKeyHashEQ.
func APIKeyHash(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldAPIKeyHash, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldIsDefault, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeploymentIDEQ applies the EQ predicate on the "deployment_id" field.
func DeploymentIDEQ(v xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldDeploymentID, v))
}

// DeploymentIDNEQ applies the NEQ predicate on the "deployment_id" field.
func DeploymentIDNEQ(v xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldDeploymentID, v))
}

// DeploymentIDIn applies the In predicate on the "deployment_id" field.
func DeploymentIDIn(vs ...xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldDeploymentID, vs...))
}

// DeploymentIDNotIn applies the NotIn predicate on the "deployment_id" field.
func DeploymentIDNotIn(vs ...xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldDeploymentID, vs...))
}

// DeploymentIDGT applies the GT predicate on the "deployment_id" field.
func DeploymentIDGT(v xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldDeploymentID, v))
}

// DeploymentIDGTE applies the GTE predicate on the "deployment_id" field.
func DeploymentIDGTE(v xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldDeploymentID, v))
}

// DeploymentIDLT applies the LT predicate on the "deployment_id" field.
func DeploymentIDLT(v xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldDeploymentID, v))
}

// DeploymentIDLTE applies the LTE predicate on the "deployment_id" field.
func DeploymentIDLTE(v xid.ID) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldDeploymentID, v))
}

// DeploymentIDContains applies the Contains predicate on the "deployment_id" field.
func DeploymentIDContains(v xid.ID) predicate.Tenant {
	vc := v.String()
	return predicate.Tenant(sql.FieldContains(FieldDeploymentID, vc))
}

// DeploymentIDHasPrefix applies the HasPrefix predicate on the "deployment_id" field.
func DeploymentIDHasPrefix(v xid.ID) predicate.Tenant {
	vc := v.String()
	return predicate.Tenant(sql.FieldHasPrefix(FieldDeploymentID, vc))
}

// DeploymentIDHasSuffix applies the HasSuffix predicate on the "deployment_id" field.
func DeploymentIDHasSuffix(v xid.ID) predicate.Tenant {
	vc := v.String()
	return predicate.Tenant(sql.FieldHasSuffix(FieldDeploymentID, vc))
}

// DeploymentIDIsNil applies the IsNil predicate on the "deployment_id" field.
func DeploymentIDIsNil() predicate.Tenant {
	return predicate.Tenant(sql.FieldIsNull(FieldDeploymentID))
}

// DeploymentIDNotNil applies the NotNil predicate on the "deployment_id" field.
func DeploymentIDNotNil() predicate.Tenant {
	return predicate.Tenant(sql.FieldNotNull(FieldDeploymentID))
}

// DeploymentIDEqualFold applies the EqualFold predicate on the "deployment_id" field.
func DeploymentIDEqualFold(v xid.ID) predicate.Tenant {
	vc := v.String()
	return predicate.Tenant(sql.FieldEqualFold(FieldDeploymentID, vc))
}

// DeploymentIDContainsFold applies the ContainsFold predicate on the "deployment_id" field.
func DeploymentIDContainsFold(v xid.ID) predicate.Tenant {
	vc := v.String()
	return predicate.Tenant(sql.FieldContainsFold(FieldDeploymentID, vc))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldContainsFold(FieldName, v))
}

// APIKeyHashEQ applies the EQ predicate on the "api_key_hash" field.
func APIKeyHashEQ(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldAPIKeyHash, v))
}

// APIKeyHashNEQ applies the NEQ predicate on the "api_key_hash" field.
func APIKeyHashNEQ(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldAPIKeyHash, v))
}

// APIKeyHashIn applies the In predicate on the "api_key_hash" field.
func APIKeyHashIn(vs ...string) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldAPIKeyHash, vs...))
}

// APIKeyHashNotIn applies the NotIn predicate on the "api_key_hash" field.
func APIKeyHashNotIn(vs ...string) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldAPIKeyHash, vs...))
}

// APIKeyHashGT applies the GT predicate on the "api_key_hash" field.
func APIKeyHashGT(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldAPIKeyHash, v))
}

// APIKeyHashGTE applies the GTE predicate on the "api_key_hash" field.
func APIKeyHashGTE(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldAPIKeyHash, v))
}

// APIKeyHashLT applies the LT predicate on the "api_key_hash" field.
func APIKeyHashLT(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldAPIKeyHash, v))
}

// APIKeyHashLTE applies the LTE predicate on the "api_key_hash" field.
func APIKeyHashLTE(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldAPIKeyHash, v))
}

// APIKeyHashContains applies the Contains predicate on the "api_key_hash" field.
func APIKeyHashContains(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldContains(FieldAPIKeyHash, v))
}

// APIKeyHashHasPrefix applies the HasPrefix predicate on the "api_key_hash" field.
func APIKeyHashHasPrefix(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldHasPrefix(FieldAPIKeyHash, v))
}

// APIKeyHashHasSuffix applies the HasSuffix predicate on the "api_key_hash" field.
func APIKeyHashHasSuffix(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldHasSuffix(FieldAPIKeyHash, v))
}

// APIKeyHashEqualFold applies the EqualFold predicate on the "api_key_hash" field.
func APIKeyHashEqualFold(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldEqualFold(FieldAPIKeyHash, v))
}

// APIKeyHashContainsFold applies the ContainsFold predicate on the "api_key_hash" field.
func APIKeyHashContainsFold(v string) predicate.Tenant {
	return predicate.Tenant(sql.FieldContainsFold(FieldAPIKeyHash, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldIsDefault, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Tenant {
	return predicate.Tenant(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasDocuments applies the HasEdge predicate on the "documents" edge.
func HasDocuments() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DocumentsTable, DocumentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentsWith applies the HasEdge predicate on the "documents" edge with a given conditions (other predicates).
func HasDocumentsWith(preds ...predicate.Document) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newDocumentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIngestJobs applies the HasEdge predicate on the "ingest_jobs" edge.
func HasIngestJobs() predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IngestJobsTable, IngestJobsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIngestJobsWith applies the HasEdge predicate on the "ingest_jobs" edge with a given conditions (other predicates).
func HasIngestJobsWith(preds ...predicate.IngestJob) predicate.Tenant {
	return predicate.Tenant(func(s *sql.Selector) {
		step := newIngestJobsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tenant) predicate.Tenant {
	return predicate.Tenant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tenant) predicate.Tenant {
	return predicate.Tenant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tenant) predicate.Tenant {
	return predicate.Tenant(sql.NotPredicates(p))
}
